import type { SettingGroup } from "@/lib/panel-settings";

export type BuiltinAddonDef = {
  id: string;
  href: string;
  name: string;
  description: string;
  category: string;
  color: string;
  /** When set, show "Configured" if this settings flag is truthy */
  settingGroup?: SettingGroup;
  settingKey?: string;
};

export const BUILTIN_ADDON_CATEGORIES = [
  "Performance",
  "Device Binding",
  "Anti-Sharing",
  "DDoS / Protection",
  "Other",
  "Live + VOD",
  "Tools",
  "Monitoring",
  "Extras",
] as const;

export const BUILTIN_ADDONS: BuiltinAddonDef[] = [
  {
    id: "performance-core",
    href: "/admin/settings/performance-core",
    name: "Performance Core",
    description: "Optimized core tuning for high concurrency — built for 10K+ simultaneous connections.",
    category: "Performance",
    color: "#4ade80",
    settingGroup: "performance-core",
    settingKey: "perfCoreEnabled",
  },
  {
    id: "device-binding",
    href: "/admin/settings/device-binding",
    name: "ActiveCode Device Binding",
    description: "Strong device-bound ActiveCode auth — bind subscriptions to specific device IDs.",
    category: "Device Binding",
    color: "#22d3ee",
  },
  {
    id: "stream-fingerprint",
    href: "/admin/settings/stream-fingerprint",
    name: "Stream Fingerprint",
    description: "Invisible watermarking to trace stream leaks back to individual subscribers.",
    category: "Anti-Sharing",
    color: "#e879f9",
  },
  {
    id: "same-ip-detection",
    href: "/admin/settings/same-ip-detection",
    name: "Same-IP Detection",
    description: "Detect multi-login and credential sharing from the same IP address.",
    category: "Anti-Sharing",
    color: "#f87171",
  },
  {
    id: "apps-lock",
    href: "/admin/settings/apps-lock",
    name: "Apps Lock",
    description: "Restrict lines to approved player apps (Smarters, TiviMate, MAG, Web, etc.).",
    category: "Anti-Sharing",
    color: "#fbbf24",
    settingGroup: "apps-lock",
    settingKey: "appsLockEnabled",
  },
  {
    id: "vod-proxy",
    href: "/admin/settings/vod-proxy",
    name: "Hide VOD URLs",
    description: "Proxy VOD through the panel so upstream source URLs stay hidden from clients.",
    category: "Anti-Sharing",
    color: "#a78bfa",
    settingGroup: "vod-proxy",
    settingKey: "vodProxyEnabled",
  },
  {
    id: "ddos-shield",
    href: "/admin/settings/security",
    name: "Layer 7 DDoS Shield",
    description: "Built-in flood protection on playback and Xtream API paths with auto IP blocks.",
    category: "DDoS / Protection",
    color: "#ef4444",
    settingGroup: "security",
    settingKey: "ddosShieldEnabled",
  },
  {
    id: "server-guard",
    href: "/admin/settings/server-guard",
    name: "Server Guard",
    description: "Harden edge servers — connection limits, abuse thresholds, and guard policies.",
    category: "DDoS / Protection",
    color: "#f97316",
    settingGroup: "server-guard",
    settingKey: "serverGuardEnabled",
  },
  {
    id: "brute-force",
    href: "/admin/settings/security",
    name: "Brute-Force Protection",
    description: "Login attempt limits, lockouts, and per-IP login flood throttling.",
    category: "DDoS / Protection",
    color: "#fb923c",
    settingGroup: "security",
    settingKey: "maxLoginAttempts",
  },
  {
    id: "api-security",
    href: "/admin/settings/security",
    name: "SQL Injection & API Hardening",
    description: "Parameterized Prisma queries, API rate limits, and input validation on admin routes.",
    category: "DDoS / Protection",
    color: "#94a3b8",
    settingGroup: "security",
    settingKey: "apiRateLimitPerMin",
  },
  {
    id: "videolog",
    href: "/admin/videolog",
    name: "VideoLog",
    description: "Real-time viewer activity logging per stream and line.",
    category: "Other",
    color: "#38bdf8",
  },
  {
    id: "url-fingerprint",
    href: "/admin/settings/fingerprint",
    name: "Playback Fingerprinting",
    description: "HMAC-signed playback URLs with optional token TTL per line.",
    category: "Other",
    color: "#c084fc",
    settingGroup: "fingerprint",
    settingKey: "enabled",
  },
  {
    id: "tmdb",
    href: "/admin/settings/tmdb",
    name: "TMDB Auto-Sync",
    description: "Auto-fetch posters, plots, and genres from TMDB on import and add-stream flows.",
    category: "Live + VOD",
    color: "#01b4e4",
    settingGroup: "tmdb",
    settingKey: "apiKey",
  },
  {
    id: "mass-tools",
    href: "/admin/management/mass-edit",
    name: "Mass Tools",
    description: "Bulk edit lines, streams, users, and categories from one workspace.",
    category: "Live + VOD",
    color: "#34d399",
  },
  {
    id: "m3u-import",
    href: "/admin/import/m3u",
    name: "One-Click M3U Import",
    description: "Import live channels from M3U/URL with category and bouquet assignment.",
    category: "Tools",
    color: "#2dd4bf",
  },
  {
    id: "epg-auto-map",
    href: "/admin/epg/channels",
    name: "Auto EPG Mapping",
    description: "Map stream names to EPG channels automatically during import and sync.",
    category: "Tools",
    color: "#60a5fa",
  },
  {
    id: "prefix-manager",
    href: "/admin/settings/prefix-manager",
    name: "Prefix & Logo Tools",
    description: "Channel prefix rules, logo auto-fetch, and branding presets.",
    category: "Tools",
    color: "#f472b6",
    settingGroup: "prefix-manager",
    settingKey: "prefixManagerEnabled",
  },
  {
    id: "viewer-geography",
    href: "/admin/analytics/viewer-heatmap",
    name: "World Map",
    description: "Live connection geography with country, region, city, and bandwidth tracking.",
    category: "Monitoring",
    color: "#22c55e",
  },
  {
    id: "resource-charts",
    href: "/admin/servers/resource-charts",
    name: "Resource Monitor",
    description: "CPU, RAM, and disk usage charts per streaming server.",
    category: "Monitoring",
    color: "#818cf8",
  },
  {
    id: "bandwidth",
    href: "/admin/analytics/bandwidth",
    name: "Bandwidth Monitor",
    description: "Ingress/egress bandwidth over time with peak and average snapshots.",
    category: "Monitoring",
    color: "#14b8a6",
  },
  {
    id: "disk-monitor",
    href: "/admin/settings/disk-monitor",
    name: "Disk Monitor",
    description: "Disk usage alerts and thresholds before imports or updates fill the VPS.",
    category: "Monitoring",
    color: "#64748b",
    settingGroup: "disk-monitor",
    settingKey: "diskMonitorEnabled",
  },
  {
    id: "stream-rank",
    href: "/admin/stream_rank",
    name: "Top Channels",
    description: "Popularity ranking — see which channels viewers watch most.",
    category: "Monitoring",
    color: "#eab308",
  },
  {
    id: "batch-manager",
    href: "/admin/settings/batch-manager",
    name: "Batch ActiveCode",
    description: "Generate ActiveCodes in bulk with prefixes and package templates.",
    category: "Extras",
    color: "#34d399",
    settingGroup: "batch-manager",
    settingKey: "batchManagerEnabled",
  },
  {
    id: "expiry-videos",
    href: "/admin/settings/expiry-videos",
    name: "Custom Expiry Videos",
    description: "Branded messages when lines expire, suspend, or run low on credits.",
    category: "Extras",
    color: "#f43f5e",
    settingGroup: "expiry-videos",
    settingKey: "expiryVideosEnabled",
  },
  {
    id: "server-cleaner",
    href: "/admin/settings/server-cleaner",
    name: "Server Cleaner",
    description: "Automated cleanup — orphaned streams, expired lines, old logs, temp files, DB vacuum.",
    category: "Extras",
    color: "#94a3b8",
    settingGroup: "server-cleaner",
    settingKey: "cleanerEnabled",
  },
];

export function builtinAddonsByCategory(): { category: string; items: BuiltinAddonDef[] }[] {
  return BUILTIN_ADDON_CATEGORIES.map((category) => ({
    category,
    items: BUILTIN_ADDONS.filter((a) => a.category === category),
  })).filter((g) => g.items.length > 0);
}
