import type { FreeRadioStation } from "@/lib/free-radio-stations";

/** DAB / national broadcast streams (UK & US). Verify licensing for your region. */
export const DAB_RADIO_STATIONS: FreeRadioStation[] = [
  {
    id: "bbc-radio-1",
    name: "BBC Radio 1",
    country: "uk",
    countryName: "United Kingdom",
    streamUrl: "https://stream.live.vc.bbcmedia.co.uk/bbc_radio_one",
    genre: "DAB",
  },
  {
    id: "bbc-radio-2",
    name: "BBC Radio 2",
    country: "uk",
    countryName: "United Kingdom",
    streamUrl: "https://stream.live.vc.bbcmedia.co.uk/bbc_radio_two",
    genre: "DAB",
  },
  {
    id: "bbc-radio-6",
    name: "BBC Radio 6 Music",
    country: "uk",
    countryName: "United Kingdom",
    streamUrl: "https://stream.live.vc.bbcmedia.co.uk/bbc_6music",
    genre: "DAB",
  },
  {
    id: "lbc-uk",
    name: "LBC",
    country: "uk",
    countryName: "United Kingdom",
    streamUrl: "https://media-ssl.musicradio.com/LBCUK",
    genre: "DAB",
  },
  {
    id: "capital-uk",
    name: "Capital UK",
    country: "uk",
    countryName: "United Kingdom",
    streamUrl: "https://media-ssl.musicradio.com/CapitalUK",
    genre: "DAB",
  },
  {
    id: "heart-uk",
    name: "Heart UK",
    country: "uk",
    countryName: "United Kingdom",
    streamUrl: "https://media-ssl.musicradio.com/HeartUK",
    genre: "DAB",
  },
  {
    id: "npr-news-us",
    name: "NPR News",
    country: "us",
    countryName: "United States",
    streamUrl: "https://npr-ice.streamguys1.com/live.mp3",
    genre: "DAB",
  },
  {
    id: "wcpe-us",
    name: "WCPE (Classical)",
    country: "us",
    countryName: "United States",
    streamUrl: "https://ice23.securenetsystems.net/WCPE",
    genre: "DAB",
  },
  {
    id: "kexp-us",
    name: "KEXP Seattle",
    country: "us",
    countryName: "United States",
    streamUrl: "https://kexp-mp3-128.streamguys1.com/kexp128.mp3",
    genre: "DAB",
  },
  {
    id: "wqxr-us",
    name: "WQXR (NYC Classical)",
    country: "us",
    countryName: "United States",
    streamUrl: "https://stream.wqxr.org/wqxr",
    genre: "DAB",
  },
];
