/** Public XMLTV guides from xtream-masters.com/epg/ */
export const EPG_COUNTRIES = [
  {
    code: "all_sources",
    name: "All Sources",
    url: "https://xtream-masters.com/epg/ALL_SOURCES1.xml.gz",
  },
  { code: "ae", name: "United Arab Emirates", url: "https://xtream-masters.com/epg/AE1.xml.gz" },
  { code: "al", name: "Albania", url: "https://xtream-masters.com/epg/AL1.xml.gz" },
  { code: "aljazeera", name: "Al Jazeera", url: "https://xtream-masters.com/epg/ALJAZEERA1.xml.gz" },
  { code: "ar", name: "Argentina", url: "https://xtream-masters.com/epg/AR1.xml.gz" },
  { code: "au", name: "Australia", url: "https://xtream-masters.com/epg/AU1.xml.gz" },
  { code: "at", name: "Austria", url: "https://xtream-masters.com/epg/AT1.xml.gz" },
  { code: "be", name: "Belgium", url: "https://xtream-masters.com/epg/BE2.xml.gz" },
  { code: "bein", name: "BeIN Sports", url: "https://xtream-masters.com/epg/BEIN1.xml.gz" },
  { code: "br", name: "Brazil", url: "https://xtream-masters.com/epg/BR1.xml.gz" },
  { code: "bg", name: "Bulgaria", url: "https://xtream-masters.com/epg/BG1.xml.gz" },
  { code: "ca", name: "Canada", url: "https://xtream-masters.com/epg/CA2.xml.gz" },
  { code: "ch", name: "Switzerland", url: "https://xtream-masters.com/epg/CH1.xml.gz" },
  { code: "cz", name: "Czech Republic", url: "https://xtream-masters.com/epg/CZ1.xml.gz" },
  { code: "de", name: "Germany", url: "https://xtream-masters.com/epg/DE1.xml.gz" },
  {
    code: "germany_magentatv",
    name: "Germany — Magenta TV",
    url: "https://xtream-masters.com/epg/germany_web.magentatv.de.xml",
  },
  {
    code: "germany_sky",
    name: "Germany — Sky",
    url: "https://xtream-masters.com/epg/germany_sky.de.xml",
  },
  { code: "es", name: "Spain", url: "https://xtream-masters.com/epg/ES1.xml.gz" },
  { code: "fr", name: "France", url: "https://xtream-masters.com/epg/FR1.xml.gz" },
  { code: "uk", name: "United Kingdom", url: "https://xtream-masters.com/epg/UK1.xml.gz" },
  { code: "gr", name: "Greece", url: "https://xtream-masters.com/epg/GR1.xml.gz" },
  { code: "hk", name: "Hong Kong", url: "https://xtream-masters.com/epg/HK1.xml.gz" },
  { code: "hr", name: "Croatia", url: "https://xtream-masters.com/epg/HR1.xml.gz" },
  { code: "hu", name: "Hungary", url: "https://xtream-masters.com/epg/HU1.xml.gz" },
  { code: "in", name: "India", url: "https://xtream-masters.com/epg/IN1.xml.gz" },
  {
    code: "india_dishtv",
    name: "India — Dish TV",
    url: "https://xtream-masters.com/epg/india_dishtv.in.xml",
  },
  {
    code: "india_tataplay",
    name: "India — Tata Play",
    url: "https://xtream-masters.com/epg/india_tataplay.xml.gz",
  },
  { code: "it", name: "Italy", url: "https://xtream-masters.com/epg/IT1.xml.gz" },
  { code: "nl", name: "Netherlands", url: "https://xtream-masters.com/epg/NL1.xml.gz" },
  { code: "pl", name: "Poland", url: "https://xtream-masters.com/epg/PL1.xml.gz" },
  { code: "plex", name: "Plex", url: "https://xtream-masters.com/epg/PLEX1.xml.gz" },
  { code: "pt", name: "Portugal", url: "https://xtream-masters.com/epg/PT1.xml.gz" },
  {
    code: "portugal_meo",
    name: "Portugal — MEO",
    url: "https://xtream-masters.com/epg/portugal_meo.pt.xml",
  },
  {
    code: "portugal_nostv",
    name: "Portugal — NOS",
    url: "https://xtream-masters.com/epg/portugal_nostv.pt.xml",
  },
  { code: "rakuten", name: "Rakuten", url: "https://xtream-masters.com/epg/RAKUTEN1.xml.gz" },
  { code: "ro", name: "Romania", url: "https://xtream-masters.com/epg/RO1.xml.gz" },
  { code: "rs", name: "Serbia", url: "https://xtream-masters.com/epg/RS1.xml.gz" },
  { code: "se", name: "Sweden", url: "https://xtream-masters.com/epg/SE1.xml.gz" },
  { code: "tr", name: "Turkey", url: "https://xtream-masters.com/epg/TR1.xml.gz" },
  { code: "us", name: "United States", url: "https://xtream-masters.com/epg/US2.xml.gz" },
  { code: "us_locals", name: "United States — Locals", url: "https://xtream-masters.com/epg/US_LOCALS1.xml.gz" },
  { code: "us_sports", name: "United States — Sports", url: "https://xtream-masters.com/epg/US_SPORTS1.xml.gz" },
] as const;
