/** Public XMLTV guides (iptv-org EPG pattern). Verify URLs periodically in production. */
export const EPG_COUNTRIES = [
  {
    code: "ww",
    name: "Worldwide (combined)",
    url: "https://iptv-org.github.io/epg/guides/ww.xml",
  },
  { code: "us", name: "United States", url: "https://iptv-org.github.io/epg/guides/us.xml" },
  { code: "uk", name: "United Kingdom", url: "https://iptv-org.github.io/epg/guides/uk.xml" },
  { code: "de", name: "Germany", url: "https://iptv-org.github.io/epg/guides/de.xml" },
  { code: "fr", name: "France", url: "https://iptv-org.github.io/epg/guides/fr.xml" },
  { code: "es", name: "Spain", url: "https://iptv-org.github.io/epg/guides/es.xml" },
  { code: "it", name: "Italy", url: "https://iptv-org.github.io/epg/guides/it.xml" },
  { code: "nl", name: "Netherlands", url: "https://iptv-org.github.io/epg/guides/nl.xml" },
  { code: "pl", name: "Poland", url: "https://iptv-org.github.io/epg/guides/pl.xml" },
  { code: "pt", name: "Portugal", url: "https://iptv-org.github.io/epg/guides/pt.xml" },
  { code: "br", name: "Brazil", url: "https://iptv-org.github.io/epg/guides/br.xml" },
  { code: "ar", name: "Argentina", url: "https://iptv-org.github.io/epg/guides/ar.xml" },
  { code: "mx", name: "Mexico", url: "https://iptv-org.github.io/epg/guides/mx.xml" },
  { code: "ca", name: "Canada", url: "https://iptv-org.github.io/epg/guides/ca.xml" },
  { code: "au", name: "Australia", url: "https://iptv-org.github.io/epg/guides/au.xml" },
  { code: "in", name: "India", url: "https://iptv-org.github.io/epg/guides/in.xml" },
  { code: "tr", name: "Turkey", url: "https://iptv-org.github.io/epg/guides/tr.xml" },
  { code: "ru", name: "Russia", url: "https://iptv-org.github.io/epg/guides/ru.xml" },
  { code: "ua", name: "Ukraine", url: "https://iptv-org.github.io/epg/guides/ua.xml" },
  { code: "gr", name: "Greece", url: "https://iptv-org.github.io/epg/guides/gr.xml" },
  { code: "se", name: "Sweden", url: "https://iptv-org.github.io/epg/guides/se.xml" },
  { code: "no", name: "Norway", url: "https://iptv-org.github.io/epg/guides/no.xml" },
  { code: "dk", name: "Denmark", url: "https://iptv-org.github.io/epg/guides/dk.xml" },
  { code: "fi", name: "Finland", url: "https://iptv-org.github.io/epg/guides/fi.xml" },
  { code: "cz", name: "Czech Republic", url: "https://iptv-org.github.io/epg/guides/cz.xml" },
  { code: "ro", name: "Romania", url: "https://iptv-org.github.io/epg/guides/ro.xml" },
  { code: "hu", name: "Hungary", url: "https://iptv-org.github.io/epg/guides/hu.xml" },
  { code: "bg", name: "Bulgaria", url: "https://iptv-org.github.io/epg/guides/bg.xml" },
  { code: "hr", name: "Croatia", url: "https://iptv-org.github.io/epg/guides/hr.xml" },
  { code: "rs", name: "Serbia", url: "https://iptv-org.github.io/epg/guides/rs.xml" },
  { code: "sk", name: "Slovakia", url: "https://iptv-org.github.io/epg/guides/sk.xml" },
  { code: "be", name: "Belgium", url: "https://iptv-org.github.io/epg/guides/be.xml" },
  { code: "ch", name: "Switzerland", url: "https://iptv-org.github.io/epg/guides/ch.xml" },
  { code: "at", name: "Austria", url: "https://iptv-org.github.io/epg/guides/at.xml" },
  { code: "ie", name: "Ireland", url: "https://iptv-org.github.io/epg/guides/ie.xml" },
  { code: "nz", name: "New Zealand", url: "https://iptv-org.github.io/epg/guides/nz.xml" },
  { code: "za", name: "South Africa", url: "https://iptv-org.github.io/epg/guides/za.xml" },
  { code: "ae", name: "United Arab Emirates", url: "https://iptv-org.github.io/epg/guides/ae.xml" },
  { code: "sa", name: "Saudi Arabia", url: "https://iptv-org.github.io/epg/guides/sa.xml" },
  { code: "il", name: "Israel", url: "https://iptv-org.github.io/epg/guides/il.xml" },
  { code: "jp", name: "Japan", url: "https://iptv-org.github.io/epg/guides/jp.xml" },
  { code: "kr", name: "South Korea", url: "https://iptv-org.github.io/epg/guides/kr.xml" },
  { code: "cn", name: "China", url: "https://iptv-org.github.io/epg/guides/cn.xml" },
  { code: "tw", name: "Taiwan", url: "https://iptv-org.github.io/epg/guides/tw.xml" },
  { code: "hk", name: "Hong Kong", url: "https://iptv-org.github.io/epg/guides/hk.xml" },
  { code: "sg", name: "Singapore", url: "https://iptv-org.github.io/epg/guides/sg.xml" },
  { code: "th", name: "Thailand", url: "https://iptv-org.github.io/epg/guides/th.xml" },
  { code: "vn", name: "Vietnam", url: "https://iptv-org.github.io/epg/guides/vn.xml" },
  { code: "ph", name: "Philippines", url: "https://iptv-org.github.io/epg/guides/ph.xml" },
  { code: "id", name: "Indonesia", url: "https://iptv-org.github.io/epg/guides/id.xml" },
  { code: "my", name: "Malaysia", url: "https://iptv-org.github.io/epg/guides/my.xml" },
  { code: "al", name: "Albania", url: "https://iptv-org.github.io/epg/guides/al.xml" },
  { code: "ba", name: "Bosnia", url: "https://iptv-org.github.io/epg/guides/ba.xml" },
  { code: "mk", name: "North Macedonia", url: "https://iptv-org.github.io/epg/guides/mk.xml" },
  { code: "si", name: "Slovenia", url: "https://iptv-org.github.io/epg/guides/si.xml" },
  { code: "lt", name: "Lithuania", url: "https://iptv-org.github.io/epg/guides/lt.xml" },
  { code: "lv", name: "Latvia", url: "https://iptv-org.github.io/epg/guides/lv.xml" },
  { code: "ee", name: "Estonia", url: "https://iptv-org.github.io/epg/guides/ee.xml" },
  { code: "co", name: "Colombia", url: "https://iptv-org.github.io/epg/guides/co.xml" },
  { code: "cl", name: "Chile", url: "https://iptv-org.github.io/epg/guides/cl.xml" },
  { code: "pe", name: "Peru", url: "https://iptv-org.github.io/epg/guides/pe.xml" },
  { code: "ve", name: "Venezuela", url: "https://iptv-org.github.io/epg/guides/ve.xml" },
  { code: "eg", name: "Egypt", url: "https://iptv-org.github.io/epg/guides/eg.xml" },
  { code: "ma", name: "Morocco", url: "https://iptv-org.github.io/epg/guides/ma.xml" },
  { code: "ng", name: "Nigeria", url: "https://iptv-org.github.io/epg/guides/ng.xml" },
  { code: "ke", name: "Kenya", url: "https://iptv-org.github.io/epg/guides/ke.xml" },
  { code: "pk", name: "Pakistan", url: "https://iptv-org.github.io/epg/guides/pk.xml" },
  { code: "bd", name: "Bangladesh", url: "https://iptv-org.github.io/epg/guides/bd.xml" },
  { code: "ir", name: "Iran", url: "https://iptv-org.github.io/epg/guides/ir.xml" },
  { code: "iq", name: "Iraq", url: "https://iptv-org.github.io/epg/guides/iq.xml" },
  { code: "lb", name: "Lebanon", url: "https://iptv-org.github.io/epg/guides/lb.xml" },
  { code: "jo", name: "Jordan", url: "https://iptv-org.github.io/epg/guides/jo.xml" },
  { code: "qa", name: "Qatar", url: "https://iptv-org.github.io/epg/guides/qa.xml" },
  { code: "kw", name: "Kuwait", url: "https://iptv-org.github.io/epg/guides/kw.xml" },
  { code: "om", name: "Oman", url: "https://iptv-org.github.io/epg/guides/om.xml" },
  { code: "bh", name: "Bahrain", url: "https://iptv-org.github.io/epg/guides/bh.xml" },
  { code: "cy", name: "Cyprus", url: "https://iptv-org.github.io/epg/guides/cy.xml" },
  { code: "mt", name: "Malta", url: "https://iptv-org.github.io/epg/guides/mt.xml" },
  { code: "is", name: "Iceland", url: "https://iptv-org.github.io/epg/guides/is.xml" },
  { code: "lu", name: "Luxembourg", url: "https://iptv-org.github.io/epg/guides/lu.xml" },
  { code: "md", name: "Moldova", url: "https://iptv-org.github.io/epg/guides/md.xml" },
  { code: "by", name: "Belarus", url: "https://iptv-org.github.io/epg/guides/by.xml" },
  { code: "kz", name: "Kazakhstan", url: "https://iptv-org.github.io/epg/guides/kz.xml" },
  { code: "uz", name: "Uzbekistan", url: "https://iptv-org.github.io/epg/guides/uz.xml" },
  { code: "ge", name: "Georgia", url: "https://iptv-org.github.io/epg/guides/ge.xml" },
  { code: "am", name: "Armenia", url: "https://iptv-org.github.io/epg/guides/am.xml" },
  { code: "az", name: "Azerbaijan", url: "https://iptv-org.github.io/epg/guides/az.xml" },
  { code: "uy", name: "Uruguay", url: "https://iptv-org.github.io/epg/guides/uy.xml" },
  { code: "py", name: "Paraguay", url: "https://iptv-org.github.io/epg/guides/py.xml" },
  { code: "bo", name: "Bolivia", url: "https://iptv-org.github.io/epg/guides/bo.xml" },
  { code: "ec", name: "Ecuador", url: "https://iptv-org.github.io/epg/guides/ec.xml" },
  { code: "cr", name: "Costa Rica", url: "https://iptv-org.github.io/epg/guides/cr.xml" },
  { code: "pa", name: "Panama", url: "https://iptv-org.github.io/epg/guides/pa.xml" },
  { code: "gt", name: "Guatemala", url: "https://iptv-org.github.io/epg/guides/gt.xml" },
  { code: "do", name: "Dominican Republic", url: "https://iptv-org.github.io/epg/guides/do.xml" },
  { code: "cu", name: "Cuba", url: "https://iptv-org.github.io/epg/guides/cu.xml" },
  { code: "pr", name: "Puerto Rico", url: "https://iptv-org.github.io/epg/guides/pr.xml" },
  { code: "tn", name: "Tunisia", url: "https://iptv-org.github.io/epg/guides/tn.xml" },
  { code: "dz", name: "Algeria", url: "https://iptv-org.github.io/epg/guides/dz.xml" },
  { code: "gh", name: "Ghana", url: "https://iptv-org.github.io/epg/guides/gh.xml" },
  { code: "sn", name: "Senegal", url: "https://iptv-org.github.io/epg/guides/sn.xml" },
  { code: "ad", name: "Andorra", url: "https://iptv-org.github.io/epg/guides/ad.xml" },
  { code: "mc", name: "Monaco", url: "https://iptv-org.github.io/epg/guides/mc.xml" },
] as const;
