/** Free internet radio streams (public URLs). Verify licensing for your deployment region. */
export type FreeRadioStation = {
  id: string;
  name: string;
  country: string;
  countryName: string;
  streamUrl: string;
  genre?: string;
};

export const FREE_RADIO_STATIONS: FreeRadioStation[] = [
  {
    id: "soma-fm-groove",
    name: "SomaFM Groove Salad",
    country: "us",
    countryName: "United States",
    streamUrl: "https://ice2.somafm.com/groovesalad-128-mp3",
    genre: "Ambient",
  },
  {
    id: "soma-fm-drone",
    name: "SomaFM Drone Zone",
    country: "us",
    countryName: "United States",
    streamUrl: "https://ice2.somafm.com/dronezone-128-mp3",
    genre: "Ambient",
  },
  {
    id: "soma-fm-indie",
    name: "SomaFM Indie Pop Rocks",
    country: "us",
    countryName: "United States",
    streamUrl: "https://ice2.somafm.com/indiepop-128-mp3",
    genre: "Indie",
  },
  {
    id: "france-inter",
    name: "France Inter",
    country: "fr",
    countryName: "France",
    streamUrl: "https://icecast.radiofrance.fr/franceinter-midfi.mp3",
    genre: "News/Talk",
  },
  {
    id: "bbc-radio-1",
    name: "BBC Radio 1 (UK)",
    country: "uk",
    countryName: "United Kingdom",
    streamUrl: "https://stream.live.vc.bbcmedia.co.uk/bbc_radio_one",
    genre: "Pop",
  },
  {
    id: "radio-swiss-jazz",
    name: "Radio Swiss Jazz",
    country: "ch",
    countryName: "Switzerland",
    streamUrl: "http://stream.srg-ssr.ch/m/rsj/mp3_128.m3u",
    genre: "Jazz",
  },
  {
    id: "radio-swiss-classic",
    name: "Radio Swiss Classic",
    country: "ch",
    countryName: "Switzerland",
    streamUrl: "http://stream.srg-ssr.ch/m/rsc_de/mp3_128.m3u",
    genre: "Classical",
  },
  {
    id: "wdr-2",
    name: "WDR 2 (Germany)",
    country: "de",
    countryName: "Germany",
    streamUrl: "https://wdr-wdr2-live.icecastssl.wdr.de/wdr/wdr2/live/mp3/128/stream.mp3",
    genre: "Pop",
  },
  {
    id: "radio-italia",
    name: "Radio Italia",
    country: "it",
    countryName: "Italy",
    streamUrl: "https://radioitaliasmi.akamaized.net/hls/live/2093120/RISMI/master.m3u8",
    genre: "Pop",
  },
  {
    id: "cadena-ser",
    name: "Cadena SER",
    country: "es",
    countryName: "Spain",
    streamUrl: "https://playerservices.streamtheworld.com/api/livestream-redirect/CADENASER.mp3",
    genre: "News",
  },
  {
    id: "radio-canada-premiere",
    name: "ICI Radio-Canada Première",
    country: "ca",
    countryName: "Canada",
    streamUrl: "https://rcavlive.akamaized.net/hls/live/2033316/RC-PREMIERE/master.m3u8",
    genre: "News",
  },
  {
    id: "abc-news-radio",
    name: "ABC News Radio (AU)",
    country: "au",
    countryName: "Australia",
    streamUrl: "https://live-radio01.mediahubaustralia.com/2RNW/mp3/",
    genre: "News",
  },
  // United Kingdom
  {
    id: "bbc-radio-2",
    name: "BBC Radio 2",
    country: "uk",
    countryName: "United Kingdom",
    streamUrl: "https://stream.live.vc.bbcmedia.co.uk/bbc_radio_two",
    genre: "Pop",
  },
  {
    id: "bbc-radio-3",
    name: "BBC Radio 3",
    country: "uk",
    countryName: "United Kingdom",
    streamUrl: "https://stream.live.vc.bbcmedia.co.uk/bbc_radio_three",
    genre: "Classical",
  },
  {
    id: "bbc-radio-4",
    name: "BBC Radio 4",
    country: "uk",
    countryName: "United Kingdom",
    streamUrl: "https://stream.live.vc.bbcmedia.co.uk/bbc_radio_fourfm",
    genre: "News/Talk",
  },
  {
    id: "bbc-radio-5-live",
    name: "BBC Radio 5 Live",
    country: "uk",
    countryName: "United Kingdom",
    streamUrl: "https://stream.live.vc.bbcmedia.co.uk/bbc_radio_five_live",
    genre: "Sport/News",
  },
  {
    id: "bbc-6-music",
    name: "BBC Radio 6 Music",
    country: "uk",
    countryName: "United Kingdom",
    streamUrl: "https://stream.live.vc.bbcmedia.co.uk/bbc_6music",
    genre: "Alternative",
  },
  {
    id: "bbc-1xtra",
    name: "BBC Radio 1Xtra",
    country: "uk",
    countryName: "United Kingdom",
    streamUrl: "https://stream.live.vc.bbcmedia.co.uk/bbc_1xtra",
    genre: "Urban",
  },
  {
    id: "bbc-asian-network",
    name: "BBC Asian Network",
    country: "uk",
    countryName: "United Kingdom",
    streamUrl: "https://stream.live.vc.bbcmedia.co.uk/bbc_asian_network",
    genre: "Asian",
  },
  {
    id: "bbc-world-service",
    name: "BBC World Service",
    country: "uk",
    countryName: "United Kingdom",
    streamUrl: "https://stream.live.vc.bbcmedia.co.uk/bbc_world_service",
    genre: "News",
  },
  {
    id: "classic-fm-uk",
    name: "Classic FM",
    country: "uk",
    countryName: "United Kingdom",
    streamUrl: "https://media-ssl.musicradio.com/ClassicFM",
    genre: "Classical",
  },
  {
    id: "capital-fm-uk",
    name: "Capital FM",
    country: "uk",
    countryName: "United Kingdom",
    streamUrl: "https://media-ssl.musicradio.com/Capital",
    genre: "Pop",
  },
  {
    id: "heart-uk",
    name: "Heart",
    country: "uk",
    countryName: "United Kingdom",
    streamUrl: "https://media-ssl.musicradio.com/HeartLondon",
    genre: "Pop",
  },
  {
    id: "smooth-radio-uk",
    name: "Smooth Radio",
    country: "uk",
    countryName: "United Kingdom",
    streamUrl: "https://media-ssl.musicradio.com/SmoothLondon",
    genre: "Easy Listening",
  },
  {
    id: "lbc-uk",
    name: "LBC",
    country: "uk",
    countryName: "United Kingdom",
    streamUrl: "https://media-ssl.musicradio.com/LBC",
    genre: "News/Talk",
  },
  {
    id: "kiss-fm-uk",
    name: "Kiss FM",
    country: "uk",
    countryName: "United Kingdom",
    streamUrl: "https://media-ssl.musicradio.com/Kiss",
    genre: "Dance",
  },
  {
    id: "absolute-radio-uk",
    name: "Absolute Radio",
    country: "uk",
    countryName: "United Kingdom",
    streamUrl: "https://media-ssl.musicradio.com/AbsoluteRadio",
    genre: "Rock",
  },
  {
    id: "planet-rock-uk",
    name: "Planet Rock",
    country: "uk",
    countryName: "United Kingdom",
    streamUrl: "https://media-ssl.musicradio.com/PlanetRock",
    genre: "Rock",
  },
  {
    id: "talksport-uk",
    name: "talkSPORT",
    country: "uk",
    countryName: "United Kingdom",
    streamUrl: "https://radio.talksport.com/stream",
    genre: "Sport",
  },
  {
    id: "virgin-radio-uk",
    name: "Virgin Radio UK",
    country: "uk",
    countryName: "United Kingdom",
    streamUrl: "https://radio.virginradio.co.uk/stream",
    genre: "Rock",
  },
  // United States
  {
    id: "soma-fm-lush",
    name: "SomaFM Lush",
    country: "us",
    countryName: "United States",
    streamUrl: "https://ice2.somafm.com/lush-128-mp3",
    genre: "Ambient",
  },
  {
    id: "soma-fm-secret",
    name: "SomaFM Secret Agent",
    country: "us",
    countryName: "United States",
    streamUrl: "https://ice2.somafm.com/secretagent-128-mp3",
    genre: "Lounge",
  },
  {
    id: "soma-fm-defcon",
    name: "SomaFM DEF CON",
    country: "us",
    countryName: "United States",
    streamUrl: "https://ice2.somafm.com/defcon-128-mp3",
    genre: "Electronic",
  },
  {
    id: "soma-fm-beat",
    name: "SomaFM Beat Blender",
    country: "us",
    countryName: "United States",
    streamUrl: "https://ice2.somafm.com/beatblender-128-mp3",
    genre: "House",
  },
  {
    id: "soma-fm-metal",
    name: "SomaFM Metal Detector",
    country: "us",
    countryName: "United States",
    streamUrl: "https://ice2.somafm.com/metal-128-mp3",
    genre: "Metal",
  },
  {
    id: "soma-fm-boot",
    name: "SomaFM Boot Liquor",
    country: "us",
    countryName: "United States",
    streamUrl: "https://ice2.somafm.com/bootliquor-128-mp3",
    genre: "Country",
  },
  {
    id: "soma-fm-jazz",
    name: "SomaFM Left Coast 70s",
    country: "us",
    countryName: "United States",
    streamUrl: "https://ice2.somafm.com/lc70s-128-mp3",
    genre: "70s",
  },
  {
    id: "npr-news",
    name: "NPR News",
    country: "us",
    countryName: "United States",
    streamUrl: "https://npr-ice.streamguys1.com/live.mp3",
    genre: "News",
  },
  {
    id: "kexp-seattle",
    name: "KEXP Seattle",
    country: "us",
    countryName: "United States",
    streamUrl: "https://kexp-mp3-128.streamguys1.com/kexp128.mp3",
    genre: "Alternative",
  },
  {
    id: "wfmu",
    name: "WFMU",
    country: "us",
    countryName: "United States",
    streamUrl: "https://wfmu.streamguys1.com/wfmu-freeform-high",
    genre: "Freeform",
  },
  {
    id: "jazz24",
    name: "Jazz24",
    country: "us",
    countryName: "United States",
    streamUrl: "https://live.wostreaming.net/direct/ppm-jazz24aac-ibc1",
    genre: "Jazz",
  },
  {
    id: "radioparadise",
    name: "Radio Paradise",
    country: "us",
    countryName: "United States",
    streamUrl: "https://stream.radioparadise.com/aac-320",
    genre: "Eclectic",
  },
  {
    id: "wnyc-fm",
    name: "WNYC FM",
    country: "us",
    countryName: "United States",
    streamUrl: "https://wnyc-ice.streamguys1.com/wnycfm",
    genre: "News/Talk",
  },
  {
    id: "kcrw",
    name: "KCRW",
    country: "us",
    countryName: "United States",
    streamUrl: "https://kcrw.streamguys1.com/kcrw_192k_mp3_onair",
    genre: "Eclectic",
  },
  {
    id: "wqxr",
    name: "WQXR Classical",
    country: "us",
    countryName: "United States",
    streamUrl: "https://stream.wqxr.org/wqxr",
    genre: "Classical",
  },
  {
    id: "kusc-classical",
    name: "KUSC Classical",
    country: "us",
    countryName: "United States",
    streamUrl: "https://playerservices.streamtheworld.com/api/livestream-redirect/KUSCMP3.mp3",
    genre: "Classical",
  },
  {
    id: "smooth-jazz-us",
    name: "Smooth Jazz Global",
    country: "us",
    countryName: "United States",
    streamUrl: "https://playerservices.streamtheworld.com/api/livestream-redirect/SMOOTHJAZZ.mp3",
    genre: "Jazz",
  },
];
