import type { AgentNginxConfig } from "@/lib/stream-agent-config";

export function buildNginxAgentSnippet(nginx: AgentNginxConfig): string {
  const liveBuf = nginx.bufferLive ? "on" : "off";
  const vodBuf = nginx.bufferVod ? "on" : "off";
  const antiFreezeNote =
    liveBuf === "off"
      ? "# Anti-Freeze: live proxy_buffering off — reduces freeze on channel zaps\n"
      : "";
  return `# Generated by Nexlify panel — include in stream server http {}
# Path: /etc/nexlify-agent/nginx-snippet.conf
${antiFreezeNote}
proxy_buffering ${liveBuf};
proxy_buffer_size ${nginx.proxyBufferSize};
proxy_buffers ${nginx.bufferCountLive} ${nginx.bufferSizeLive};
proxy_read_timeout ${nginx.readTimeout}s;
proxy_connect_timeout ${nginx.connectionTimeout}s;
send_timeout ${nginx.readTimeout}s;

# VOD / on-demand locations can override:
# proxy_buffering ${vodBuf};
# proxy_buffers ${nginx.bufferCountVod} ${nginx.bufferSizeVod};

# HLS packaging hint (configure in your app block):
# hls_fragment ${nginx.hlsSegmentDuration}s;
`;
}
