import { prisma } from "@/lib/prisma";

export const SETTING_GROUPS = [
  "general",
  "community",
  "streams",
  "cache",
  "backup",
  "tmdb",
  "notifications",
  "monitoring",
  "billing",
  "cron",
  "security",
  "fingerprint",
  "binaries",
  "domains",
  "server",
  "geo",
  "theft",
  "integrations",
  "player",
  "webrtc",
  "catchup",
  "white-label",
  "server-guard",
  "performance-core",
  "auto-fix",
  "lb-redirect",
  "cloud-backup",
  "server-cleaner",
  "vod-proxy",
  "apps-lock",
  "stream-analyzer",
  "source-swap",
  "source-monitor",
  "prefix-manager",
  "batch-manager",
  "expiry-videos",
  "disk-monitor",
  "transcoding-pack",
  "lb-pro",
  "archive-pack",
  "security-shield",
  "analytics-ai",
  "dvr-pack",
  "compliance-audit",
  "live-sports",
] as const;

export type SettingGroup = (typeof SETTING_GROUPS)[number];

const DEFAULTS: Record<SettingGroup, Record<string, unknown>> = {
  general: {
    panelName: "Nexlify",
    panelUrl: "",
    webhookUrls: "",
    webhookEvents: "*",
    timezone: "UTC",
    defaultLanguage: "en",
    maintenanceMode: false,
    disableTrial: false,
  },
  community: {
    telegramUrl: "",
    discordUrl: "",
    signalUrl: "",
  },
  server: {
    serverUrl: "",
    magServerUrl: "",
    enigmaServerUrl: "",
    panelPort: 3000,
    panelSslPort: 443,
    streamHttpPort: 8080,
    streamHttpsPort: 443,
    repoPath: "",
    lastPanelUpdate: null as {
      at: string;
      ok: boolean;
      message: string;
      fromVersion: string;
      toVersion: string;
    } | null,
    updateHistory: [] as {
      at: string;
      ok: boolean;
      message: string;
      fromVersion: string;
      toVersion: string;
      action: "update" | "rollback";
      steps?: { name: string; ok: boolean; output: string }[];
    }[],
    rollbackGitRef: null as string | null,
    updateCheckUrl: "",
    panelUpdateAutoDownload: true,
    streamAgentUpgradeNotes:
      "Upgrade stream agents: Admin → Servers → action menu → Reinstall agent, or SSH to the node and re-run the install command from the server wizard. Match agent version to panel release shown on Updates.",
  },
  streams: {
    defaultStreamTimeout: 30,
    maxConnectionsPerLine: 1,
    allowRestream: false,
    epgHoursAhead: 48,
    vodDirectPlay: true,
    excludeDisabledFromExport: true,
    connectionLimitHandle: "validate_on_connect",
    vodConnectionHandle: "30m_expire",
    loadBalancing: "server_slots",
    geoLoadBalancing: true,
    loadBalancingRestriction: "stop_overloaded",
    streamConnectionsOnRestart: "keep",
    nginxBufferLive: false,
    nginxBufferVod: false,
    nginxRestreamUseBuffer: false,
    nginxBufferCountLive: 96,
    nginxBufferCountVod: 96,
    nginxBufferSizeLive: "32k",
    nginxBufferSizeVod: "32k",
    hlsSegmentDuration: 6,
    segmentLength: 10,
    bufferSize: "512k",
    readTimeout: 30,
    connectionTimeout: 10,
    maxConnectionsPerStream: 0,
    ffmpegThreadCount: 0,
    transcodePreset: "veryfast",
    defaultFfmpegProfile: "copy",
    preferredLiveOutput: "hls",
    antiBufferNotes: "",
    antiFreezeEnabled: true,
    fastZapEnabled: true,
    playbackUrlCacheTtlSec: 60,
    zapPrefetchNeighbors: 3,
    zapPrefetchOnLiveHit: true,
    zapPrefetchOnPlaylist: true,
    autoChannelLogos: true,
    autoChannelLogoSource: "tmdb_then_slug",
    onDemandProbesize: "128000",
    onDemandProbesizeAuto: true,
    abrAutoSwitch: true,
    playbackTokenTtlSec: 0,
    autoFixDeadLinks: true,
    autoFixDeadLinksIntervalMin: 15,
    catchupPresetsHours: [24, 48, 72],
  },
  cache: {
    statsTtlSeconds: 15,
    epgTtlSeconds: 120,
    categoriesTtlSeconds: 30,
    playbackUrlCacheTtlSec: 30,
    redisMode: "single",
    redisClusterNodes: "",
    redisMaxMemory: "",
    redisKeyPrefix: "nexlify:",
    flushOnPanelUpdate: false,
    notes: "",
  },
  backup: {
    enabled: true,
    scheduleCron: "0 3 * * *",
    target: "local",
    localPath: "",
    remoteProtocol: "sftp",
    remoteHost: "",
    remotePort: 22,
    remoteUser: "",
    remotePassword: "",
    remotePath: "/backups/nexlify",
    keepDays: 7,
    fullExportOnBackup: true,
    allowRestoreUpload: true,
    exportFormat: "json",
    s3Bucket: "",
    s3Region: "",
    s3AccessKey: "",
    s3SecretKey: "",
    pgDumpCronEnabled: false,
    pgDumpCronSchedule: "0 4 * * *",
    pgDumpDocUrl: "/admin/settings/server#pg-dump",
  },
  tmdb: {
    apiKey: "",
    language: "en-US",
    enableMovieMeta: true,
    enableSeriesMeta: true,
    enableLiveEpgMeta: false,
    autoFetchOnImport: true,
    preferOriginalTitle: false,
    cacheTtlHours: 24,
    fallbackLanguage: "en-US",
    notes: "",
  },
  notifications: {
    emailEnabled: false,
    notifyEmail: "",
    smtpHost: "",
    smtpPort: 587,
    smtpUser: "",
    smtpPassword: "",
    notifyNewLine: true,
    notifyLowCredits: true,
    notifyTicketReply: true,
    smsEnabled: false,
    twilioAccountSid: "",
    twilioAuthToken: "",
    twilioFromNumber: "",
    smsNotifyExpiry: true,
    smsNotifyRenewal: true,
    smsNotifySuspension: true,
    smsNotifyLowCredit: true,
    notifyExpiry: true,
    notifyRenewal: true,
    notifySuspension: true,
    notifyLowCreditThreshold: 50,
    notifyExpiryDaysBefore: 3,
    inPanelAlerts: true,
    resellerNotifyEmail: "",
    resellerNotifyPhone: "",
  },
  monitoring: {
    telegramAlertsEnabled: false,
    telegramBotToken: "",
    telegramChatId: "",
    alertOfflineStreams: true,
    alertHighLoad: true,
    alertAbuse: true,
    highLoadConnectionsThreshold: 500,
    offlineStreamMinutes: 5,
  },
  billing: {
    paypalClientId: "",
    paypalClientSecret: "",
    paypalSandbox: true,
    paypalWebhookUrl: "",
    stripePublishableKey: "",
    stripeSecretKey: "",
    stripeWebhookSecret: "",
    stripeTestMode: true,
    stripeWebhookUrl: "",
    coinbaseApiKey: "",
    coinbaseWebhookSecret: "",
    coinbaseWebhookUrl: "",
    coinbaseTestMode: true,
    cryptomusApiKey: "",
    cryptomusMerchantId: "",
    cryptomusWebhookSecret: "",
    cryptomusTestMode: true,
    binanceApiKey: "",
    binanceSecretKey: "",
    binanceWebhookSecret: "",
    binanceTestMode: true,
    couponCheckoutEnabled: true,
    notes: "Payment credentials for website checkout integration (WHMCS or custom store).",
  },
  cron: {
    epgSyncEnabled: true,
    epgSyncCron: "0 * * * *",
    channelRefreshEnabled: true,
    channelRefreshCron: "0 4 * * *",
    deadLinkProbeEnabled: true,
    deadLinkProbeCron: "*/15 * * * *",
    subscriptionNotifyCron: "0 8 * * *",
    notes: "Requires PM2 nexlify-cron. Hourly jobs use runHourlyCronJobs; others run each minute cycle when due.",
  },
  security: {
    forceHttps: false,
    sessionDays: 7,
    ipWhitelist: "",
    logoutOnIpChange: false,
    maxLoginAttempts: 10,
    lockoutMinutes: 15,
    loginFloodPerMin: 30,
    requireStrongPasswords: false,
    autoGenerateLineCredentials: true,
    lineCredentialMinLength: 6,
    apiRateLimitPerMin: 120,
    totpRequiredForAdmins: false,
    totpRequiredForResellers: false,
    blockBots: true,
    stealthPanel: true,
    ddosShieldEnabled: true,
    ddosShieldPerIpPerMin: 300,
    ddosShieldBlockMinutes: 15,
    trustCloudflareIp: true,
    trustBunnyIp: true,
    cloudflareIpv4: "",
    cloudflareIpv6: "",
    bunnyIpv4: "",
    cdnIpsSyncedAt: null as string | null,
  },
  fingerprint: {
    enabled: false,
    algorithm: "sha256",
    includeUserAgent: true,
    includeClientIp: true,
    secret: "",
    leakAuditEnabled: true,
    leakAuditRetentionDays: 30,
  },
  domains: {
    primaryDomain: "",
    extraDomains: [] as string[],
    sslEnabled: false,
    forceHttps: false,
    fullSslEncryption: false,
    certbotEmail: "",
    certFullChainPath: "",
    certKeyPath: "",
    lastCertbotRun: null as {
      at: string;
      ok: boolean;
      message: string;
      domains: string[];
    } | null,
  },
  binaries: {
    binRoot: "/home/nexlify/bin",
    nginxPath: "/home/nexlify/bin/nginx/1.29.0/sbin/nginx",
    nginxRtmpPath: "/home/nexlify/bin/nginx_rtmp/sbin/nginx",
    ffmpegPath: "/home/nexlify/bin/ffmpeg_bin/8.0/ffmpeg",
    activeNginxId: "nginx-129-quic",
    redisPath: "/home/nexlify/bin/redis/bin/redis-server",
    phpPath: "/home/nexlify/bin/php/bin/php",
    certbotPath: "/home/nexlify/bin/certbot/bin/certbot",
    maxmindPath: "/home/nexlify/bin/maxmind",
    daemonsSh: "/home/nexlify/bin/daemons.sh",
    useBundledOnStreamServers: true,
    activeFfmpegId: "bundled-80",
    activePhpId: "php84",
    ffmpegVersions: [] as { id: string; label: string; path: string }[],
    phpVersions: [] as { id: string; label: string; path: string }[],
    notes: "",
  },
  geo: {
    enabled: true,
    maxmindDbPath: "",
    blockVpnHosting: false,
    autoBlockVpnToBlocklist: false,
    fallbackIpApi: true,
    notes:
      "Per-line allowed/blocked countries on Manage Lines. Playback guard enforces geo at connect. MaxMind DB path overrides bundled geoip. Auto-block adds VPN/hosting IPs to the global blocklist.",
  },
  theft: {
    enabled: true,
    sameIpLineThreshold: 3,
    autoDisableLine: false,
    lookbackMinutes: 10,
    vodTheftEnabled: true,
    vodSameIpLineThreshold: 2,
    streamTheftEnabled: true,
    streamSameIpLineThreshold: 3,
  },
  integrations: {
    plexDefaultPort: 32400,
    youtubeImportAsLive: true,
  },
  player: {
    builtInCdm: true,
    widevineEnabled: true,
    playreadyEnabled: false,
    webrtcPreviewEnabled: true,
    licenseProxyUrl: "",
    cdmNotes: "Built-in Widevine CDM for the panel player and stream probe.",
  },
  webrtc: {
    enabled: false,
    gatewayMode: "mediamtx",
    gatewayBaseUrl: "",
    mediamtxApiUrl: "http://127.0.0.1:9997",
    webrtcPathPrefix: "live",
    stunUrls: "stun:stun.l.google.com:19302,stun:stun1.l.google.com:19302",
    turnUrl: "",
    turnUsername: "",
    turnCredential: "",
    fallbackToHls: true,
    lowLatencyTargetMs: 500,
    sessionTtlSec: 3600,
    webrtcPort: 8889,
  },
  catchup: {
    catchupEnabled: false,
    catchupDays: 7,
    catchupStoragePath: "/var/catchup",
    catchupMaxFileSize: 2048,
    catchupQuality: "HD",
    catchupBitrate: 4000,
    catchupAllChannels: false,
  },
  "white-label": {
    whiteLabelAppName: "Nexlify",
    whiteLabelLogoUrl: "",
    whiteLabelFaviconUrl: "",
    whiteLabelPrimaryColor: "#00c0ef",
    whiteLabelAccentColor: "#5eb8e8",
    whiteLabelCustomCss: "",
    whiteLabelDomain: "",
  },
  "server-guard": {
    serverGuardEnabled: true,
    guardPlaylistProbing: true,
    guardBruteForce: true,
    guardDdosLayer7: true,
    guardResourceExhaustion: true,
    guardAutoBlockMinutes: 15,
    guardMaxConnectionsPerIp: 300,
    guardCpuThreshold: 85,
    guardRamThreshold: 90,
    guardCooldownSeconds: 60,
    guardNotifyTelegram: true,
    guardNotifyEmail: true,
  },
  "performance-core": {
    perfCoreEnabled: true,
    perfLowRamMode: true,
    perfConnectionPooling: true,
    perfNginxWorkers: "auto",
    perfStreamPreload: true,
    perfEventScaleMode: "dynamic",
    perfBufferOptimization: true,
    perfConnectionReuse: true,
    perfMaxEventConnections: 50000,
  },
  "auto-fix": {
    autoFixEnabled: true,
    autoFixAudioLoss: true,
    autoFixVideoFreeze: true,
    autoFixLoopDetection: true,
    autoFixSourceSwitch: true,
    autoFixIntervalSeconds: 30,
    autoFixMaxRetries: 3,
    autoFixNotifyOnRepair: true,
  },
  "lb-redirect": {
    lbRedirectEnabled: true,
    lbEncryptGetPhp: true,
    lbEncryptStalker: true,
    lbTokenExpirySeconds: 300,
    lbForceHttps: true,
    lbSignatureAlgorithm: "sha256",
  },
  "cloud-backup": {
    cloudBackupEnabled: false,
    cloudBackupProvider: "s3",
    cloudBackupDropboxToken: "",
    cloudBackupS3Bucket: "",
    cloudBackupS3Region: "",
    cloudBackupS3AccessKey: "",
    cloudBackupS3SecretKey: "",
    cloudBackupSchedule: "0 3 * * *",
    cloudBackupRetentionDays: 30,
    cloudBackupIncludeDb: true,
    cloudBackupIncludeMedia: false,
    xDriveEnabled: false,
    xDriveApiKey: "",
    xDriveEndpoint: "",
  },
  "server-cleaner": {
    cleanerEnabled: true,
    cleanerSchedule: "0 2 * * *",
    cleanerLogRetentionDays: 7,
    cleanerTempRetentionHours: 24,
    cleanerCacheRetentionHours: 48,
    cleanerStreamLogsRetentionDays: 14,
    cleanerPanelLogsRetentionDays: 30,
    cleanerCoreDumpEnabled: true,
    cleanerOrphanedFiles: true,
    cleanerDryRun: false,
  },
  "vod-proxy": {
    vodProxyEnabled: false,
    vodProxyThroughPanel: true,
    vodProxyCacheEnabled: true,
    vodProxyCacheTtlHours: 24,
    vodProxyMaxFileSize: 2048,
    vodProxyLogAccess: true,
    vodProxyStripReferer: true,
    vodProxyUserAgent: "Nexlify/1.0",
  },
  "apps-lock": {
    appsLockEnabled: false,
    appsLockAllowedApps: [] as string[],
    appsLockBlockUnknown: true,
    appsLockEnforceOnConnect: true,
    appsLockUserAgentWhitelist: "",
    appsLockMacValidation: true,
  },
  "stream-analyzer": {
    analyzerEnabled: true,
    analyzerAudioSync: true,
    analyzerVideoBitrate: true,
    analyzerFrameDrop: true,
    analyzerResolutionMismatch: true,
    analyzerIntervalSeconds: 60,
    analyzerAutoRepair: true,
    analyzerAlertThreshold: 5,
  },
  "source-swap": {
    sourceSwapEnabled: true,
    sourceSwapOnFailure: true,
    sourceSwapOnHighLoad: true,
    sourceSwapGracePeriodMs: 5000,
    sourceSwapFailoverRetries: 2,
    sourceSwapNotifyOnChange: true,
    sourceSwapPreserveViewerPosition: true,
  },
  "source-monitor": {
    sourceMonitorEnabled: true,
    sourceMonitorIntervalSeconds: 30,
    sourceMonitorOfflineAlert: true,
    sourceMonitorLatencyAlert: true,
    sourceMonitorLatencyThresholdMs: 5000,
    sourceMonitorAutoRestart: true,
    sourceMonitorMaxRestartsPerHour: 5,
    sourceMonitorNotifyChannels: ["telegram", "email"] as string[],
  },
  "prefix-manager": {
    prefixManagerEnabled: false,
    prefixManagerLogoDns: "",
    prefixManagerChannelPrefix: "",
    prefixManagerMoviePrefix: "",
    prefixManagerSeriesPrefix: "",
    prefixManagerBulkApply: true,
    prefixManagerPreserveOriginal: false,
  },
  "batch-manager": {
    batchManagerEnabled: true,
    batchManagerDefaultCount: 100,
    batchManagerPrefix: "NEX",
    batchManagerLength: 8,
    batchManagerExpiryDays: 30,
    batchManagerBouquets: [] as string[],
    batchManagerMaxConnections: 1,
    batchManagerNotifyOnCreate: true,
  },
  "expiry-videos": {
    expiryVideosEnabled: false,
    expiryVideoUrl: "",
    expiryVideoMessage: "Your subscription has expired. Please renew to continue watching.",
    expiryVideoBranding: true,
    expiryVideoAutoPlay: true,
    expiryVideoFallbackImage: "",
    expiryVideoRedirectUrl: "",
  },
  "disk-monitor": {
    diskMonitorEnabled: true,
    diskMonitorIntervalMinutes: 15,
    diskMonitorThresholdPercent: 85,
    diskMonitorAlertChannels: ["telegram", "email"] as string[],
    diskMonitorAutoCleanup: false,
    diskMonitorCleanupTargets: [] as string[],
    diskMonitorPredictFullHours: 24,
  },
  "transcoding-pack": {
    enabled: false,
    defaultGpuEncoder: "auto",
    enableHevc: true,
    enable4K: false,
    autoFallback: true,
    realtimeQualityAdjust: true,
    vaapiDevice: "/dev/dri/renderD128",
    ladderProfile: "1080p-nvenc",
  },
  "lb-pro": {
    enabled: false,
    geoRouting: true,
    bandwidthAware: true,
    failoverOnDegraded: true,
    healthCheckIntervalSec: 30,
    cloudflareGuidance: true,
  },
  "archive-pack": {
    enabled: false,
    defaultRetentionDays: 7,
    maxRetentionDays: 30,
    storagePath: "/var/nexlify/archive",
    outputFormat: "hls",
    epgLinkedRecording: true,
    recordAllChannels: false,
  },
  "security-shield": {
    enabled: false,
    ipqsApiKey: "",
    blockVpn: true,
    blockDatacenter: true,
    blockTor: true,
    fraudScoreBlockThreshold: 85,
    fraudScoreFlagThreshold: 60,
    logConnectionSource: true,
    autoBlockFlagged: false,
  },
  "analytics-ai": {
    enabled: false,
    churnPrediction: true,
    peakHeatmaps: true,
    regionalContentRank: true,
    streamOptimizationHints: true,
    epgAiMatching: true,
    realtimeMonitor: true,
  },
  "dvr-pack": {
    enabled: false,
    storageMode: "local",
    cloudBucketUrl: "",
    defaultQuotaGb: 5,
    portalRecordingEnabled: true,
    epgScheduleEnabled: true,
  },
  "compliance-audit": {
    enabled: true,
    auditLogRetentionDays: 365,
    exportFormat: "json",
    isoComplianceNotes: "Leverage existing ISO certifications — enable detailed audit exports.",
    gdprDataExportEnabled: true,
  },
  "live-sports": {
    enabled: true,
    cacheTtlSec: 900,
    providers: [] as import("@/lib/live-sports-types").LiveSportsProvider[],
  },
};

function settingKey(group: SettingGroup) {
  return `settings.${group}`;
}

export async function getSettingGroup(group: SettingGroup): Promise<Record<string, unknown>> {
  const row = await prisma.panelSetting.findUnique({ where: { key: settingKey(group) } });
  const base = { ...DEFAULTS[group] };
  if (!row?.value) return base;
  try {
    return { ...base, ...(JSON.parse(row.value) as Record<string, unknown>) };
  } catch {
    return base;
  }
}

export async function setSettingGroup(group: SettingGroup, data: Record<string, unknown>) {
  const merged = { ...DEFAULTS[group], ...data };
  await prisma.panelSetting.upsert({
    where: { key: settingKey(group) },
    create: { key: settingKey(group), value: JSON.stringify(merged) },
    update: { value: JSON.stringify(merged) },
  });
  return merged;
}

export async function getAllSettings() {
  const out: Record<string, Record<string, unknown>> = {};
  for (const g of SETTING_GROUPS) {
    out[g] = await getSettingGroup(g);
  }
  return out;
}

/** Community links (migrated from general when community group is empty). */
export async function getCommunityLinksSettings(): Promise<{
  telegramUrl: string;
  discordUrl: string;
  signalUrl: string;
}> {
  const community = await getSettingGroup("community");
  const general = await getSettingGroup("general");
  return {
    telegramUrl: String(community.telegramUrl ?? general.telegramUrl ?? ""),
    discordUrl: String(community.discordUrl ?? general.discordUrl ?? ""),
    signalUrl: String(community.signalUrl ?? general.signalUrl ?? ""),
  };
}
