export type XuiApiAction = {
  action: string;
  group: string;
  params: string;
};

/** Documented XUI-compatible actions on GET/POST /api/v1?api_key=&action= */
export const XUI_API_ACTIONS: XuiApiAction[] = [
  { action: "create_line", group: "Lines", params: "username, password, days, max_connections, bouquets | package_id" },
  { action: "edit_line", group: "Lines", params: "id, username?, password?, days?, max_connections?" },
  { action: "get_line", group: "Lines", params: "id" },
  { action: "get_lines", group: "Lines", params: "limit?" },
  { action: "disable_line", group: "Lines", params: "id" },
  { action: "enable_line", group: "Lines", params: "id" },
  { action: "ban_line", group: "Lines", params: "id" },
  { action: "unban_line", group: "Lines", params: "id" },
  { action: "delete_line", group: "Lines", params: "id" },
  { action: "renew_line", group: "Lines", params: "id, days" },
  { action: "set_line_bouquets", group: "Lines", params: "id, bouquets" },
  { action: "kick_user", group: "Lines", params: "id" },
  { action: "create_reseller", group: "Resellers", params: "username, password, credits?" },
  { action: "add_credits", group: "Resellers", params: "username, credits" },
  { action: "get_resellers", group: "Resellers", params: "limit?" },
  { action: "get_reg_users", group: "Resellers", params: "limit?" },
  { action: "edit_user", group: "Resellers", params: "id, credits?, is_active?" },
  { action: "delete_user", group: "Resellers", params: "id" },
  { action: "create_staff", group: "Resellers", params: "username, password" },
  { action: "get_users", group: "Resellers", params: "limit?" },
  { action: "user_info", group: "Resellers", params: "username" },
  { action: "get_bouquets", group: "Content", params: "" },
  { action: "create_bouquet", group: "Content", params: "name" },
  { action: "edit_bouquet", group: "Content", params: "id, name?" },
  { action: "delete_bouquet", group: "Content", params: "id" },
  { action: "reorder_bouquets", group: "Content", params: "ids" },
  { action: "add_stream_to_bouquet", group: "Content", params: "bouquet_id, stream_id" },
  { action: "remove_stream_from_bouquet", group: "Content", params: "bouquet_id, stream_id" },
  { action: "get_bouquet_streams", group: "Content", params: "id" },
  { action: "assign_bouquet_to_reseller", group: "Content", params: "user_id, bouquet_id" },
  { action: "get_streams", group: "Content", params: "type?" },
  { action: "get_movies", group: "Content", params: "" },
  { action: "get_series", group: "Content", params: "" },
  { action: "create_stream", group: "Content", params: "name, stream_url, type?" },
  { action: "edit_stream", group: "Content", params: "id, name?, stream_url?" },
  { action: "delete_stream", group: "Content", params: "id" },
  { action: "start_stream", group: "Content", params: "id" },
  { action: "stop_stream", group: "Content", params: "id" },
  { action: "restart_stream", group: "Content", params: "id" },
  { action: "mass_enable_streams", group: "Content", params: "ids" },
  { action: "mass_disable_streams", group: "Content", params: "ids" },
  { action: "get_categories", group: "Content", params: "category_type?" },
  { action: "create_category", group: "Content", params: "name, type?" },
  { action: "edit_category", group: "Content", params: "id, name?" },
  { action: "delete_category", group: "Content", params: "id" },
  { action: "get_packages", group: "Billing", params: "" },
  { action: "get_servers", group: "Servers", params: "" },
  { action: "get_server", group: "Servers", params: "id" },
  { action: "get_processes", group: "Servers", params: "" },
  { action: "apply_server_config", group: "Servers", params: "id?" },
  { action: "reload_nginx", group: "Servers", params: "id?" },
  { action: "get_transcodes", group: "Servers", params: "" },
  { action: "live_connections", group: "Stats", params: "" },
  { action: "activity_logs", group: "Stats", params: "limit?" },
  { action: "get_analytics", group: "Stats", params: "" },
  { action: "get_dashboard", group: "Stats", params: "" },
  { action: "get_connection_stats", group: "Stats", params: "" },
  { action: "get_events", group: "Stats", params: "" },
  { action: "get_mag", group: "Devices", params: "" },
  { action: "create_mag", group: "Devices", params: "mac, package_id?" },
  { action: "delete_mag", group: "Devices", params: "id" },
  { action: "get_epg", group: "EPG", params: "" },
  { action: "set_epg_channel", group: "EPG", params: "stream_id, epg_channel_id" },
  { action: "sync_epg", group: "EPG", params: "" },
  { action: "get_access_codes", group: "Security", params: "" },
];
