#!/usr/bin/env bash
# Apply playback topology: local-edge | remote-splice | multi-lb | classic-lb.
# Never fuser :8080. Never start nexlify-iptv-edge on remote-splice / multi-lb / classic-lb.
set -euo pipefail

PANEL_DIR="${PANEL_DIR:-/opt/nexlify-panel}"
[ -d "$PANEL_DIR" ] || PANEL_DIR="/home/nexlify-panel"
cd "$PANEL_DIR"

# shellcheck disable=SC1091
. "$PANEL_DIR/scripts/playback-topology.sh"
# shellcheck disable=SC1091
[ -f "$PANEL_DIR/scripts/panel-no-local-iptv-edge.sh" ] && . "$PANEL_DIR/scripts/panel-no-local-iptv-edge.sh"

set -a
# shellcheck disable=SC1091
[ -f .env ] && . ./.env
set +a

# shellcheck disable=SC1091
[ -f "$PANEL_DIR/scripts/live-routing-env.sh" ] && . "$PANEL_DIR/scripts/live-routing-env.sh"
if type nexlify_load_routing_autodetect >/dev/null 2>&1; then
  nexlify_load_routing_autodetect
  nexlify_ensure_playback_topology_file
fi

MODE="$(nexlify_playback_topology)"
[ -z "$MODE" ] && MODE="${NEXLIFY_LIVE_EDGE_MODE:-local-edge}"
MODE="$(echo "$MODE" | tr '[:upper:]' '[:lower:]' | tr '_' '-')"
case "$MODE" in
  remote|split|remote-edge|b) MODE="remote-splice" ;;
  local|a) MODE="local-edge" ;;
  c|lb|multi-server) MODE="multi-lb" ;;
  d|ffmpeg-lb|xui-lb|nginx-ffmpeg) MODE="classic-lb" ;;
esac

if type nexlify_panel_must_not_run_iptv_edge >/dev/null 2>&1 && nexlify_panel_must_not_run_iptv_edge; then
  case "$MODE" in
    classic-lb) ;;
    *) MODE="remote-splice" ;;
  esac
fi

REMOTE="${NEXLIFY_REMOTE_EDGE:-}"
if [ -z "$REMOTE" ] && [ -f /etc/nexlify/playback-topology ]; then
  REMOTE="$(sed -n '2p' /etc/nexlify/playback-topology | tr -d '\r')"
fi

case "$MODE" in
  remote-splice)
    if [ -z "$REMOTE" ]; then
      echo "WARN: remote-splice without NEXLIFY_REMOTE_EDGE — not rewriting nginx; not starting local edge"
      if type nexlify_stop_panel_local_iptv_edge >/dev/null 2>&1; then
        nexlify_stop_panel_local_iptv_edge
      fi
      echo "topology_ok mode=remote-splice nginx_unchanged"
      exit 0
    fi
    export NEXLIFY_REMOTE_EDGE="$REMOTE"
    if [ -x "$PANEL_DIR/scripts/restore-live-proxy.sh" ]; then
      LIVE_ROUTING_FORCE=1 bash "$PANEL_DIR/scripts/restore-live-proxy.sh"
    else
      bash "$PANEL_DIR/scripts/route-live-to-remote-edge.sh"
    fi
    if type nexlify_stop_panel_local_iptv_edge >/dev/null 2>&1; then
      nexlify_stop_panel_local_iptv_edge
    fi
    echo "topology_ok mode=remote-splice"
    ;;
  multi-lb)
    # Horizontal stream nodes: stop local iptv-edge; optionally publish nginx
    # upstream list from NEXLIFY_LB_UPSTREAMS=host:port,host:port
    if type nexlify_stop_panel_local_iptv_edge >/dev/null 2>&1; then
      nexlify_stop_panel_local_iptv_edge
    fi
    UPS="${NEXLIFY_LB_UPSTREAMS:-}"
    if [ -z "$UPS" ] && [ -n "${NEXLIFY_REMOTE_EDGE:-}" ]; then
      UPS="$NEXLIFY_REMOTE_EDGE"
    fi
    if [ -n "$UPS" ]; then
      CONF="/etc/nginx/conf.d/nexlify-multi-lb-upstreams.conf"
      chattr -i "$CONF" 2>/dev/null || true
      {
        echo "# Generated by apply-live-edge-topology.sh (multi-lb)"
        echo "upstream nexlify_multi_lb {"
        OLDIFS=$IFS
        IFS=,
        for ep in $UPS; do
          ep="$(echo "$ep" | tr -d '[:space:]')"
          [ -n "$ep" ] || continue
          echo "    server ${ep} max_fails=3 fail_timeout=10s;"
        done
        IFS=$OLDIFS
        echo "    keepalive 64;"
        echo "}"
      } > "$CONF"
      if [ -x "$PANEL_DIR/scripts/restore-live-proxy.sh" ]; then
        # First upstream becomes the proxy target for co-located Main routing.
        FIRST="$(echo "$UPS" | cut -d, -f1 | tr -d '[:space:]')"
        export NEXLIFY_REMOTE_EDGE="$FIRST"
        export NEXLIFY_CLASSIC_LB_UPSTREAM="$FIRST"
        LIVE_ROUTING_FORCE=1 bash "$PANEL_DIR/scripts/restore-live-proxy.sh" || true
      fi
      nginx -t 2>/dev/null && systemctl reload nginx 2>/dev/null || true
      echo "topology_ok mode=multi-lb upstreams=${UPS}"
    else
      echo "topology_ok mode=multi-lb — panel will not bind local iptv-edge (set NEXLIFY_LB_UPSTREAMS=host:port,... to publish upstreams)"
    fi
    ;;
  classic-lb)
    # XUI co-located: Main :80/:443/:8080 proxy media → classic-lb; LB :8090 also plays.
    if [ -z "$REMOTE" ]; then
      if [ -f /etc/nexlify-lb/lb.env ] || ss -lntp 2>/dev/null | grep -qE ':8090\b'; then
        echo "classic-lb: co-located — using 127.0.0.1:8090"
        REMOTE="127.0.0.1:8090"
      else
        echo "WARN: classic-lb without NEXLIFY_REMOTE_EDGE and no local :8090 — defaulting 127.0.0.1:8090"
        REMOTE="127.0.0.1:8090"
      fi
    fi
    export NEXLIFY_REMOTE_EDGE="$REMOTE"
    export NEXLIFY_CLASSIC_LB=1
    export NEXLIFY_PLAYBACK_TOPOLOGY=classic-lb
    # Co-located classic-lb always proxies via loopback (public IP:8090 still works for clients)
    if [ -f /etc/nexlify-lb/lb.env ] || ss -lntp 2>/dev/null | grep -qE ':8090\b'; then
      export NEXLIFY_CLASSIC_LB_UPSTREAM="${NEXLIFY_CLASSIC_LB_UPSTREAM:-127.0.0.1:8090}"
    fi
    if [ -x "$PANEL_DIR/scripts/restore-live-proxy.sh" ]; then
      LIVE_ROUTING_FORCE=1 bash "$PANEL_DIR/scripts/restore-live-proxy.sh"
    else
      bash "$PANEL_DIR/scripts/route-live-to-remote-edge.sh"
    fi
    if type nexlify_stop_panel_local_iptv_edge >/dev/null 2>&1; then
      nexlify_stop_panel_local_iptv_edge
    fi
    echo "topology_ok mode=classic-lb — XUI Main+LB; stop nexlify-iptv-edge on this host"
    ;;
  local-edge|*)
    rm -f /etc/nginx/conf.d/nexlify-live-remote-edge.conf 2>/dev/null || true
    if command -v nginx >/dev/null 2>&1; then
      nginx -t 2>/dev/null && systemctl reload nginx 2>/dev/null || true
    fi
    if [ "${NEXLIFY_USE_IPTV_EDGE:-1}" = "1" ] && [ -f "$PANEL_DIR/scripts/install-iptv-edge-proxy.sh" ]; then
      bash "$PANEL_DIR/scripts/install-iptv-edge-proxy.sh"
    fi
    echo "topology_ok mode=local-edge"
    ;;
esac
