#!/usr/bin/env bash
# Install / refresh Nexlify HTTP stream edge (Xtream / M3U / live / MAG).
# Supports primary + extra HTTP listen ports from .env (STREAM_HTTP_EXTRA_PORTS).
#
# IMPORTANT: nginx cannot share TCP ports with the Node IPTV edge. When
# NEXLIFY_USE_IPTV_EDGE is enabled (default on modern installs), ports such as
# 8080/25461/(optional 443) are skipped here so edge owns them and nginx keeps :80.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# shellcheck source=scripts/nexlify-port-registry.sh
source "$ROOT/scripts/nexlify-port-registry.sh"
nexlify_load_ports_from_env "$ROOT"

DEST="/etc/nginx/conf.d/nexlify-stream-edge.conf"
EXTRA_DEST="/etc/nginx/conf.d/nexlify-stream-extra.conf"
PANEL_HTTP_DEST="/etc/nginx/conf.d/nexlify-panel-http.conf"
UPSTREAM="/etc/nginx/conf.d/nexlify-upstream.conf"
STREAM_PORT="$NEXLIFY_PORT_STREAM_HTTP"
EDGE_OWNED="$(nexlify_iptv_edge_owned_ports "$ROOT")"

nexlify_read_env_file() {
  grep "^${1}=" "$ROOT/.env" 2>/dev/null | head -1 | cut -d= -f2- | sed -e 's/^["'\'' ]*//' -e 's/["'\'' ]*$//' || true
}

STREAM_HTTP_EXTRA="$(nexlify_read_env_file STREAM_HTTP_EXTRA_PORTS)"
PANEL_LISTEN="$(nexlify_read_env_file PORT)"
[ -z "$PANEL_LISTEN" ] && PANEL_LISTEN="13000"

resolve_edge_port() {
  local p
  p="$(nexlify_read_env_file STREAM_EDGE_PORT)"
  if [ -n "$p" ]; then
    echo "$p"
    return
  fi
  p="$(nexlify_read_env_file STREAM_HTTP_PORT)"
  if [ -n "$p" ] && [ "$p" != "$PANEL_LISTEN" ]; then
    echo "$p"
    return
  fi
  for p in $EDGE_OWNED; do
    case "$p" in
      8080) echo 8080; return ;;
      25461) echo 25461; return ;;
    esac
  done
  echo "8080"
}

EDGE_PORT="$(resolve_edge_port)"

write_upstream_conf() {
  local panel_listen="$1"
  mkdir -p "$(dirname "$UPSTREAM")"
  cat > "$UPSTREAM" <<UP
# Shared upstreams — generated by install-nginx-stream-edge.sh
upstream nexlify_panel {
    least_conn;
    server 127.0.0.1:${panel_listen};
    keepalive 512;
}
UP
}

port_owned_by_edge() {
  local port="$1" p
  for p in $EDGE_OWNED; do
    [ "$p" = "$port" ] && return 0
  done
  return 1
}

collect_http_ports() {
  local ports="$1"
  local extra="${2:-}"
  extra="${extra//,/ }"
  local result="$ports"
  for p in $extra; do
    [ -z "$p" ] && continue
    result="$result $p"
  done
  echo "$result" | tr ' ' '\n' | awk '!seen[$0]++ && $0 != ""' | tr '\n' ' '
}

ALL_PORTS_RAW="$(collect_http_ports "$STREAM_PORT" "$STREAM_HTTP_EXTRA")"
ALL_PORTS=""
SKIPPED=""
for p in $ALL_PORTS_RAW; do
  if port_owned_by_edge "$p"; then
    SKIPPED="$SKIPPED $p"
    continue
  fi
  ALL_PORTS="$ALL_PORTS $p"
done
ALL_PORTS="${ALL_PORTS# }"
SKIPPED="${SKIPPED# }"
if [ -n "$SKIPPED" ]; then
  echo "[stream-edge] Skipping nginx listen on IPTV-edge ports: $SKIPPED (edge owns these; nginx keeps :80)"
fi

write_stream_locations() {
  local fwd_port="$1"
  local upstream_target="${2:-http://nexlify_panel}"
  cat <<LOC
    location = /xmltv.php {
        gzip off;
        if (\$request_method = OPTIONS) {
            add_header Access-Control-Allow-Origin "*";
            add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS";
            add_header Access-Control-Allow-Headers "Content-Type, User-Agent, Accept, Range";
            add_header Content-Length 0;
            return 204;
        }
        add_header Access-Control-Allow-Origin "*" always;
        add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Content-Type, User-Agent, Accept, Range" always;
        proxy_pass ${upstream_target};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Port ${fwd_port};
        proxy_set_header X-Nexlify-Client-Port ${fwd_port};
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto http;
        proxy_set_header Accept-Encoding "";
        proxy_read_timeout 300s;
        proxy_buffering off;
    }

    location ~ ^/(player_api\.php|panel_api\.php|get\.php|xmltv\.php|live/|timeshift/|movie/|series/|c/|stalker_portal/) {
        if (\$request_method = OPTIONS) {
            add_header Access-Control-Allow-Origin "*";
            add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS";
            add_header Access-Control-Allow-Headers "Content-Type, User-Agent, Accept, Range";
            add_header Content-Length 0;
            return 204;
        }
        add_header Access-Control-Allow-Origin "*" always;
        add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Content-Type, User-Agent, Accept, Range" always;

        proxy_pass ${upstream_target};
        proxy_http_version 1.1;
        # Preserve the listen port IPTV apps used (Next may rewrite x-forwarded-port to upstream).
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Port ${fwd_port};
        proxy_set_header X-Nexlify-Client-Port ${fwd_port};
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto http;
        proxy_read_timeout 300s;
        proxy_buffering off;
    }

    location / {
        return 404;
    }
LOC
}

# When Next listens on 127.0.0.1:13000, nginx must own public :80 for /admin and /login.
# IPTV-edge may own :443/:8080/:25461 — never assume Node still binds :80.
nginx_other_vhost_listens_80() {
  local f
  for f in /etc/nginx/conf.d/*.conf /etc/nginx/sites-enabled/*; do
    [ -f "$f" ] || continue
    [ "$(basename "$f")" = "nexlify-panel-http.conf" ] && continue
    [[ "$f" == *.disabled ]] && continue
    if grep -Eq '^[[:space:]]*listen[[:space:]]+(\[::\]:)?80([[:space:];]|$)' "$f" 2>/dev/null; then
      return 0
    fi
  done
  return 1
}

write_panel_http80_vhost() {
  local listen="${PANEL_LISTEN:-13000}"
  if [ "$listen" = "80" ]; then
    rm -f "$PANEL_HTTP_DEST" 2>/dev/null || true
    return 0
  fi
  # MovieFlix / marketing already bind :80 — a second default_server would break nginx -t.
  if nginx_other_vhost_listens_80; then
    echo "[stream-edge] :80 already has an nginx vhost — leaving it (not writing $PANEL_HTTP_DEST)"
    return 0
  fi
  local edge_port="8080"
  for p in $EDGE_OWNED; do
    case "$p" in
      8080) edge_port=8080; break ;;
      25461) edge_port=25461 ;;
    esac
  done
  mkdir -p "$(dirname "$PANEL_HTTP_DEST")"
  cat > "$PANEL_HTTP_DEST" <<NGINX
# :80 — admin UI → Next :${listen}; IPTV apps → local edge :${edge_port}
# (Sending /live through Next crash-loops workers and makes Smarters crawl.)
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    # Panel SQL dumps are ~1GB; 100m 413s POST /api/admin/migrate.
    client_max_body_size 2048m;
    large_client_header_buffers 8 64k;
    client_header_buffer_size 32k;

    location = /xmltv.php {
        gzip off;
        proxy_pass http://127.0.0.1:${edge_port};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Port \$server_port;
        proxy_set_header X-Nexlify-Client-Port \$server_port;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Accept-Encoding "";
        proxy_read_timeout 300s;
        proxy_buffering off;
    }

    location ~ ^/(player_api\.php|panel_api\.php|get\.php|xmltv\.php|live/|timeshift/|movie/|series/|c/|stalker_portal/) {
        proxy_pass http://127.0.0.1:${edge_port};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Port \$server_port;
        proxy_set_header X-Nexlify-Client-Port \$server_port;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$remote_addr;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 300s;
        proxy_buffering off;
    }

    location /api/admin/migrate {
        client_max_body_size 2048m;
        proxy_request_buffering off;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Port \$server_port;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_pass http://nexlify_panel;
    }

    location / {
        proxy_pass http://nexlify_panel;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Port \$server_port;
        proxy_read_timeout 300s;
    }
}
NGINX
  echo "[stream-edge] Panel HTTP vhost :80 UI → :${listen}, IPTV → 127.0.0.1:${edge_port} ($PANEL_HTTP_DEST)"
}

if [ "${NEXLIFY_USE_STREAM_EDGE_NGINX:-1}" != "1" ] || [ "$STREAM_PORT" = "${NEXLIFY_PORT_HTTP}" ]; then
  echo "[stream-edge] Direct HTTP on :${NEXLIFY_PORT_HTTP} — removing separate stream edge vhost"
  rm -f "$DEST" 2>/dev/null || true
  # Distro default site must not fight the panel vhost on :80.
  rm -f /etc/nginx/sites-enabled/default 2>/dev/null || true
  # Legacy RTMP in conf.d breaks nginx -t
  rm -f /etc/nginx/conf.d/nexlify-rtmp.conf 2>/dev/null || true

  # Ensure upstream matches panel listen port + IPTV edge keepalive pool
  write_upstream_conf "$PANEL_LISTEN"

  # Extra HTTP ports still need nginx → panel upstream in direct mode
  # (ports owned by IPTV edge are already filtered out of ALL_PORTS)
  EXTRA_ONLY=""
  for p in $ALL_PORTS; do
    [ "$p" = "${NEXLIFY_PORT_HTTP}" ] && continue
    [ "$p" = "$PANEL_LISTEN" ] && continue
    EXTRA_ONLY="$EXTRA_ONLY $p"
  done
  EXTRA_ONLY="${EXTRA_ONLY# }"

  if [ -n "$EXTRA_ONLY" ] && command -v nginx >/dev/null 2>&1; then
    echo "[stream-edge] Extra HTTP ports (direct mode): $EXTRA_ONLY → 127.0.0.1:${PANEL_LISTEN}"
    {
      echo "# Nexlify extra stream HTTP ports — generated $(date -u +%Y-%m-%dT%H:%M:%SZ)"
      for p in $EXTRA_ONLY; do
        echo "server {"
        echo "    listen ${p} default_server;"
        echo "    listen [::]:${p} default_server;"
        echo "    server_name _;"
        echo "    client_max_body_size 50m;"
        echo "    large_client_header_buffers 8 64k;"
        write_stream_locations "$p" "http://127.0.0.1:${PANEL_LISTEN}"
        echo "}"
        echo ""
      done
    } > "$EXTRA_DEST"
  else
    rm -f "$EXTRA_DEST" 2>/dev/null || true
    # Drop stale disabled leftovers when edge owns extras
    rm -f "${EXTRA_DEST}.disabled" 2>/dev/null || true
  fi

  write_panel_http80_vhost

  if command -v nginx >/dev/null 2>&1; then
    nginx -t
    if systemctl is-active --quiet nginx 2>/dev/null; then
      systemctl reload nginx
    else
      systemctl start nginx
    fi
  fi
  bash "$ROOT/scripts/nexlify-firewall-ports.sh" || true
  exit 0
fi

# No nginx stream ports left (all owned by IPTV edge) — keep upstream only
if [ -z "$ALL_PORTS" ]; then
  echo "[stream-edge] No nginx stream ports to bind — IPTV edge owns stream HTTP"
  rm -f "$DEST" "$EXTRA_DEST" 2>/dev/null || true
  write_panel_http80_vhost
  write_upstream_conf "$PANEL_LISTEN"
  if command -v nginx >/dev/null 2>&1; then
    nginx -t
    if systemctl is-active --quiet nginx 2>/dev/null; then
      systemctl reload nginx
    else
      systemctl start nginx
    fi
  fi
  bash "$ROOT/scripts/nexlify-firewall-ports.sh" || true
  exit 0
fi

# Legacy RTMP in conf.d breaks nginx -t
rm -f /etc/nginx/conf.d/nexlify-rtmp.conf 2>/dev/null || true

if [ ! -f "$UPSTREAM" ]; then
  echo "[stream-edge] Installing nexlify-upstream.conf…"
fi
write_upstream_conf "$PANEL_LISTEN"

{
  echo "# Nexlify stream edge — generated $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# Ports: $ALL_PORTS (one server block per port so X-Forwarded-Port is correct)"
  for p in $ALL_PORTS; do
    echo "server {"
    echo "    listen ${p} default_server;"
    echo "    listen [::]:${p} default_server;"
    echo "    server_name _;"
    echo "    client_max_body_size 50m;"
    echo "    large_client_header_buffers 8 64k;"
    write_stream_locations "$p"
    echo "}"
    echo ""
  done
} > "$DEST"

rm -f "$EXTRA_DEST" 2>/dev/null || true

nginx -t
if systemctl is-active --quiet nginx 2>/dev/null; then
  systemctl reload nginx
else
  systemctl start nginx
fi

bash "$ROOT/scripts/nexlify-firewall-ports.sh" || true

echo "[stream-edge] Ready on: $ALL_PORTS (player_api.php, get.php, live/, movie/, xmltv.php)"
