#!/usr/bin/env bash
# Nexlify Panel — Add a custom domain to an existing installation
#
#   curl -fsSL 'https://nexlify.live/install/add-domain.sh' | sudo bash -s -- --domain panel.example.com --email admin@example.com
#
# Sets up nginx reverse proxy + SSL for a custom panel domain.
# Requires: nginx, certbot, and the panel already running on port 13000.
set -euo pipefail

DOMAIN=""
EMAIL=""
PANEL_PORT="${PANEL_PORT:-13000}"
DRY_RUN=0

usage() {
  cat <<'EOF'
Nexlify Panel — Add Domain

Usage:
  curl -fsSL 'https://nexlify.live/install/add-domain.sh' | sudo bash -s -- --domain panel.example.com --email admin@example.com

Options:
  --domain DOMAIN          Your panel domain (required)
  --email EMAIL            Email for Let's Encrypt SSL (required)
  --panel-port PORT        Panel backend port (default: 13000)
  --dry-run                Test certbot without installing cert
  -h, --help               Show this help
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
    --domain) DOMAIN="${2:-}"; shift 2 ;;
    --email) EMAIL="${2:-}"; shift 2 ;;
    --panel-port) PANEL_PORT="${2:-}"; shift 2 ;;
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1"; usage; exit 1 ;;
  esac
done

log() { echo ""; echo "==> $*"; }
die() { echo "ERROR: $*" >&2; exit 1; }

[ -n "$DOMAIN" ] || die "--domain is required (e.g. panel.example.com)"
[ -n "$EMAIL" ] || die "--email is required (for Let's Encrypt SSL)"
command -v nginx >/dev/null 2>&1 || die "nginx is not installed"
command -v certbot >/dev/null 2>&1 || die "certbot is not installed"

# --- 1. Check DNS resolves to this server ---
log "Checking DNS for $DOMAIN ..."
SERVER_IP=$(curl -s4 ifconfig.me 2>/dev/null || curl -s icanhazip.com 2>/dev/null || echo "")
DOMAIN_IP=$(dig +short "$DOMAIN" A 2>/dev/null | head -1)

if [ -z "$DOMAIN_IP" ]; then
  die "DNS lookup failed — $DOMAIN does not resolve. Add an A record pointing to $SERVER_IP first."
fi

if [ "$DOMAIN_IP" != "$SERVER_IP" ]; then
  echo "  WARNING: $DOMAIN resolves to $DOMAIN_IP but this server is $SERVER_IP"
  echo "  SSL will work but traffic may not reach this server."
  echo ""
  read -p "  Continue anyway? [y/N] " -r
  [[ $REPLY =~ ^[Yy]$ ]] || exit 1
fi

log "DNS OK — $DOMAIN -> $DOMAIN_IP"

# --- 2. Create HTTP-only nginx config for certbot challenge ---
CONF="/etc/nginx/sites-available/${DOMAIN}.conf"
CONF_LINK="/etc/nginx/sites-enabled/${DOMAIN}.conf"

log "Creating HTTP-only nginx config ..."
cat > "$CONF" <<NGINX
# Auto-generated by nexlify add-domain.sh
# After SSL cert is obtained, this config is replaced with the full SSL config.

server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN};

    client_max_body_size 100m;
    large_client_header_buffers 8 64k;
    client_header_buffer_size 32k;

    location ~ ^/(player_api\.php|get\.php|xmltv\.php|live/|movie/|c/|stalker_portal/) {
        proxy_pass http://127.0.0.1:${PANEL_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 300s;
        proxy_buffering off;
    }

    location / {
        proxy_pass http://127.0.0.1:${PANEL_PORT};
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
NGINX

ln -sf "$CONF" "$CONF_LINK"

log "Testing nginx config ..."
nginx -t || die "nginx config test failed"

log "Reloading nginx ..."
systemctl reload nginx

# --- 3. Obtain SSL certificate ---
log "Obtaining SSL certificate for $DOMAIN ..."

if [ "$DRY_RUN" -eq 1 ]; then
  certbot certonly --nginx -d "$DOMAIN" --email "$EMAIL" --agree-tos --no-eff-email --dry-run
  log "Dry run passed. Run without --dry-run to install the cert."
  exit 0
fi

certbot certonly --nginx -d "$DOMAIN" --email "$EMAIL" --agree-tos --no-eff-email --non-interactive

# --- 4. Replace config with full SSL version ---
log "Updating nginx config with SSL ..."
cat > "$CONF" <<'NGINX_HEAD'
map $http_x_forwarded_proto $forwarded_proto {
    default $http_x_forwarded_proto;
    ""      $scheme;
}

NGINX_HEAD

cat >> "$CONF" <<NGINX_SSL
server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN};
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ${DOMAIN};

    ssl_certificate     /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    client_max_body_size 100m;
    large_client_header_buffers 8 64k;
    client_header_buffer_size 32k;

    location ~ ^/(player_api\.php|get\.php|xmltv\.php|live/|movie/|c/|stalker_portal/) {
        if (\$request_method = OPTIONS) {
            add_header Access-Control-Allow-Origin "*";
            add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS";
            add_header Access-Control-Allow-Headers "Content-Type, User-Agent, Accept, Range";
            add_header Content-Length 0;
            return 204;
        }
        add_header Access-Control-Allow-Origin "*" always;
        add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Content-Type, User-Agent, Accept, Range" always;
        proxy_pass http://127.0.0.1:${PANEL_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$forwarded_proto;
        proxy_read_timeout 300s;
        proxy_buffering off;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:${PANEL_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$forwarded_proto;
    }

    location / {
        proxy_pass http://127.0.0.1:${PANEL_PORT};
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$forwarded_proto;
        proxy_connect_timeout 60s;
        proxy_read_timeout 300s;
    }
}
NGINX_SSL

log "Testing nginx config ..."
nginx -t || die "nginx config test failed after SSL setup"

log "Reloading nginx ..."
systemctl reload nginx

# --- 5. Set up auto-renewal ---
log "Setting up certbot auto-renewal ..."
if ! crontab -l 2>/dev/null | grep -q certbot; then
  (crontab -l 2>/dev/null; echo "0 3 * * * certbot renew --quiet --post-hook 'systemctl reload nginx'") | crontab -
  log "Cron job added: certbot renew daily at 3 AM"
fi

# --- Done ---
echo ""
echo "============================================"
echo "  Domain $DOMAIN configured successfully!"
echo "============================================"
echo ""
echo "  Panel URL:   https://$DOMAIN"
echo "  Panel port:  $PANEL_PORT (internal)"
echo "  SSL cert:    /etc/letsencrypt/live/$DOMAIN/"
echo "  Nginx conf:  $CONF"
echo ""
echo "  Set this in your panel .env:"
echo "    PANEL_PRIMARY_DOMAIN=$DOMAIN"
echo ""
echo "  Then restart the panel:"
echo "    cd /opt/nexlify-panel && pm2 restart nexlify"
echo ""
