/**
 * AUTO-GENERATED by npm run license:sync-public-key — Ed25519 public key (safe to commit).
 * Private key: .license-keys/private.pem (never commit, never ship to customers).
 */
export const DEFAULT_LICENSE_PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAYwo0NG7c53ltWwIz2dju4S2sBo0NtnRYI3YANGKIREg=
-----END PUBLIC KEY-----
`;

export function licensePublicKeyPem(): string {
  const fromEnv = process.env.NEXLIFY_LICENSE_PUBLIC_KEY?.trim();
  if (fromEnv) {
    return fromEnv.includes("BEGIN PUBLIC KEY")
      ? fromEnv
      : Buffer.from(fromEnv, "base64").toString("utf8");
  }
  return DEFAULT_LICENSE_PUBLIC_KEY_PEM;
}
