#!/usr/bin/env bash
# Restrict panel.nexlify.live to owner IP(s) — optional staging lock
set -euo pipefail

APP_DIR="${APP_DIR:-/var/www/nexlify}"
# Must NOT live under conf.d/ — nginx includes conf.d/*.conf in the http{} block (blocks all sites).
ALLOW_CONF="/etc/nginx/panel-staging-allow.conf"
ENV_FILE="$APP_DIR/.env"

echo "=== ensure-panel-staging-access ==="

# allow/deny uses $remote_addr — must resolve visitor IP behind Cloudflare
if [ ! -f /etc/nginx/cloudflare-realip.conf ]; then
  {
    echo "# Cloudflare real IP ranges"
    curl -fsSL https://www.cloudflare.com/ips-v4 | sed 's/^/set_real_ip_from /;s/$/;/'
    curl -fsSL https://www.cloudflare.com/ips-v6 | sed 's/^/set_real_ip_from /;s/$/;/'
    echo "real_ip_header CF-Connecting-IP;"
    echo "real_ip_recursive on;"
  } > /etc/nginx/cloudflare-realip.conf
  echo "Wrote /etc/nginx/cloudflare-realip.conf"
fi

load_ips() {
  if [ -f "$ENV_FILE" ]; then
    # shellcheck disable=SC1090
    source <(grep -E '^PANEL_OWNER_IPS=' "$ENV_FILE" | sed 's/\r$//') 2>/dev/null || true
  fi
  echo "${PANEL_OWNER_IPS:-}"
}

IPS="$(load_ips | tr -d ' ')"

if [ -z "$IPS" ]; then
  cat > "$ALLOW_CONF" <<'EOF'
# Staging open — set PANEL_OWNER_IPS in /var/www/nexlify/.env and re-run ensure-panel-staging-access.sh
EOF
  echo "PANEL_OWNER_IPS not set — panel.nexlify.live is open (no IP filter)."
  echo "To lock to your IP only, add to $ENV_FILE:"
  echo '  PANEL_OWNER_IPS=YOUR.IP.HERE'
  echo "Then re-run this script."
  nginx -t && systemctl reload nginx
  exit 0
fi

{
  echo "# Generated by ensure-panel-staging-access.sh — owner staging lock"
  IFS=',' read -ra ADDR <<< "$IPS"
  for ip in "${ADDR[@]}"; do
    ip="$(echo "$ip" | xargs)"
    [ -n "$ip" ] && echo "allow $ip;"
  done
  echo "deny all;"
} > "$ALLOW_CONF"

echo "Wrote $ALLOW_CONF for: $IPS"
nginx -t
systemctl reload nginx
echo "panel.nexlify.live is now restricted to owner IP(s)."
