ALTER TABLE "PanelUser" ADD COLUMN IF NOT EXISTS "profitPercent" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Package" ADD COLUMN IF NOT EXISTS "profitPercent" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Package" ADD COLUMN IF NOT EXISTS "shopEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Package" ADD COLUMN IF NOT EXISTS "shopPriceCents" INTEGER NOT NULL DEFAULT 0;
