#!/usr/bin/env bash
# Ensure https://PANEL_IP reaches the Nexlify panel, not another site's SSL vhost
# (e.g. moviestream SPA /admin rewrite → 500 / redirect cycle).
set -euo pipefail

PANEL_DIR="${PANEL_DIR:-/opt/nexlify-panel}"
[ -f "$PANEL_DIR/package.json" ] || PANEL_DIR="/home/nexlify-panel"
ENV_FILE="$PANEL_DIR/.env"
OUT="/etc/nginx/conf.d/nexlify-panel-ssl.conf"
UPSTREAM="/etc/nginx/conf.d/nexlify-upstream.conf"

env_val() {
  # Never fail the script when a key is missing (pipefail + grep exit 1).
  local key="$1"
  [ -f "$ENV_FILE" ] || { echo ""; return 0; }
  grep -E "^${key}=" "$ENV_FILE" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"' | tr -d "'" || true
}

names=()
add_name() {
  local n="${1:-}"
  n="$(echo "$n" | tr '[:upper:]' '[:lower:]' | sed -e 's#^https\?://##' -e 's#/.*##' -e 's#:.*##' -e 's/"//g' -e "s/'//g" | xargs 2>/dev/null || true)"
  [ -z "$n" ] && return 0
  for existing in "${names[@]:-}"; do
    [ "$existing" = "$n" ] && return 0
  done
  names+=("$n")
}

# Always include the machine's public/private IPs first (customer IP installs).
for ip in $(hostname -I 2>/dev/null || true); do
  add_name "$ip"
done

if [ -f "$ENV_FILE" ]; then
  add_name "$(env_val PANEL_PRIMARY_DOMAIN)"
  add_name "$(env_val NEXT_PUBLIC_SERVER_URL)"
  extras="$(env_val PANEL_EXTRA_DOMAINS)"
  IFS=',' read -ra EXTRA_ARR <<< "${extras:-}"
  for e in "${EXTRA_ARR[@]:-}"; do add_name "$e"; done
fi
add_name "panel.demo.nexlify.live"

NAMES="${names[*]}"
echo "Panel HTTPS names: $NAMES"

# Ensure upstream exists (IP installs listen on :80; domain installs often :13000).
PANEL_LISTEN="$(env_val PORT)"
[ -z "$PANEL_LISTEN" ] && PANEL_LISTEN="$(env_val PANEL_PORT)"
[ -z "$PANEL_LISTEN" ] && PANEL_LISTEN="80"
mkdir -p /etc/nginx/conf.d
if [ ! -f "$UPSTREAM" ] || ! grep -q 'upstream nexlify_panel' "$UPSTREAM" 2>/dev/null; then
  cat > "$UPSTREAM" <<UP
# Generated by fix-panel-https-default.sh — panel listen port ${PANEL_LISTEN}
upstream nexlify_panel {
    least_conn;
    server 127.0.0.1:${PANEL_LISTEN};
    keepalive 32;
}
UP
fi

CERT_DIR="/etc/nginx/ssl/nexlify-panel"
mkdir -p "$CERT_DIR"
FIRST_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
[ -z "$FIRST_IP" ] && FIRST_IP="127.0.0.1"

need_cert=0
if [ ! -f "$CERT_DIR/fullchain.pem" ] || [ ! -f "$CERT_DIR/privkey.pem" ]; then
  need_cert=1
elif ! openssl x509 -in "$CERT_DIR/fullchain.pem" -noout -text 2>/dev/null | grep -q "$FIRST_IP"; then
  need_cert=1
fi

if [ "$need_cert" = "1" ]; then
  if [ -f /etc/letsencrypt/live/panel.demo.nexlify.live/fullchain.pem ]; then
    ln -sfn /etc/letsencrypt/live/panel.demo.nexlify.live/fullchain.pem "$CERT_DIR/fullchain.pem"
    ln -sfn /etc/letsencrypt/live/panel.demo.nexlify.live/privkey.pem "$CERT_DIR/privkey.pem"
  else
    SAN="IP:${FIRST_IP}"
    for n in "${names[@]:-}"; do
      if echo "$n" | grep -Eq '^[0-9.]+$'; then SAN="$SAN,IP:$n"; else SAN="$SAN,DNS:$n"; fi
    done
    openssl req -x509 -nodes -newkey rsa:2048 -days 825 \
      -keyout "$CERT_DIR/privkey.pem" \
      -out "$CERT_DIR/fullchain.pem" \
      -subj "/CN=${FIRST_IP}" \
      -addext "subjectAltName=${SAN}" 2>/dev/null \
      || openssl req -x509 -nodes -newkey rsa:2048 -days 825 \
           -keyout "$CERT_DIR/privkey.pem" \
           -out "$CERT_DIR/fullchain.pem" \
           -subj "/CN=${FIRST_IP}"
  fi
fi

cat > "$OUT" <<NGINX
# Managed by fix-panel-https-default.sh — panel HTTPS default_server
# Self-signed IP cert is intentional for https://PANEL_IP (IPTV apps).
server {
    listen 443 ssl http2 default_server;
    listen [::]:443 ssl http2 default_server;
    server_name ${NAMES} _;

    ssl_certificate     ${CERT_DIR}/fullchain.pem;
    ssl_certificate_key ${CERT_DIR}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    client_max_body_size 100m;
    large_client_header_buffers 8 64k;

    # Preserve client Host even when apps paste http(s):// into DNS —
    # the panel sanitizes scheme from Host for server_info.url.
    location / {
        proxy_pass http://nexlify_panel;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Nexlify-Client-Port 443;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_connect_timeout 60s;
        proxy_read_timeout 300s;
        proxy_buffering off;
    }
}
NGINX

nginx -t
systemctl reload nginx
echo "Panel HTTPS default_server installed ($OUT) for: $NAMES"
ss -tlnp | grep -E ':443\b' || echo "WARN: nothing listening on :443 after reload"
