#!/usr/bin/env bash
# Install nginx load balancer in front of multiple IPTV edge nodes.
#
#   EDGE_IPS="45.88.138.18,75.119.137.174" \
#   STREAM_HOST=darkcdn.store \
#   EDGE_PORT=8080 \
#   bash scripts/install-multi-edge-lb.sh
#
# Requires nginx. Does not modify panel or edge PM2 — LB VPS only.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

EDGE_IPS="${EDGE_IPS:-}"
STREAM_HOST="${STREAM_HOST:-stream.local}"
EDGE_PORT="${EDGE_PORT:-8080}"
CONF="/etc/nginx/conf.d/nexlify-multi-edge-lb.conf"

if [ -z "$EDGE_IPS" ]; then
  echo "ERROR: set EDGE_IPS=ip1,ip2,..."
  exit 1
fi

IFS=',' read -ra IPS <<< "$EDGE_IPS"
upstream=""
for ip in "${IPS[@]}"; do
  ip="$(echo "$ip" | xargs)"
  [ -z "$ip" ] && continue
  upstream="${upstream}    server ${ip}:${EDGE_PORT} max_fails=3 fail_timeout=10s;
"
done

if [ -z "$upstream" ]; then
  echo "ERROR: no valid IPs in EDGE_IPS"
  exit 1
fi

mkdir -p "$(dirname "$CONF")"
cat > "$CONF" <<NGINX
# Generated by install-multi-edge-lb.sh — $(date -Iseconds)
upstream nexlify_iptv_edges {
    least_conn;
${upstream}}

server {
    listen 80;
    listen [::]:80;
    server_name ${STREAM_HOST};

    client_max_body_size 0;
    proxy_buffering off;
    proxy_read_timeout 300s;
    proxy_connect_timeout 10s;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;

    location ~ ^/(live|movie|series|timeshift)/ {
        proxy_pass http://nexlify_iptv_edges;
    }

    location ~ ^/(player_api\.php|panel_api\.php|get\.php|xmltv\.php|portal\.php) {
        proxy_pass http://nexlify_iptv_edges;
    }

    location / {
        return 404;
    }
}
NGINX

echo "[multi-edge-lb] wrote $CONF for ${STREAM_HOST} → ${EDGE_IPS}:${EDGE_PORT}"
if command -v nginx >/dev/null 2>&1; then
  nginx -t
  systemctl reload nginx || nginx -s reload
  echo "[multi-edge-lb] nginx reloaded"
else
  echo "[multi-edge-lb] WARN: nginx not found — install config manually"
fi
