#!/usr/bin/env node
/**
 * Generate Ed25519 license signing keys (KEEP PRIVATE KEY SECRET).
 * Public key is written into src/lib/license/public-key.ts
 */
import { generateKeyPairSync, randomBytes } from "crypto";
import fs from "fs";
import path from "path";

const root = process.cwd();
const keysDir = path.join(root, ".license-keys");
const pubOut = path.join(root, "src", "lib", "license", "public-key.ts");

const { publicKey, privateKey } = generateKeyPairSync("ed25519");
const pubPem = publicKey.export({ type: "spki", format: "pem" });
const privPem = privateKey.export({ type: "pkcs8", format: "pem" });

fs.mkdirSync(keysDir, { recursive: true });
fs.writeFileSync(path.join(keysDir, "private.pem"), privPem, { mode: 0o600 });
fs.writeFileSync(path.join(keysDir, "public.pem"), pubPem);

const escaped = pubPem.replace(/\\/g, "\\\\").replace(/`/g, "\\`");
const ts = `/**
 * AUTO-GENERATED by npm run license:setup — Ed25519 public key (safe to commit).
 * Private key: .license-keys/private.pem (never commit, never ship to customers).
 */
export const DEFAULT_LICENSE_PUBLIC_KEY_PEM = \`${pubPem}\`;

export function licensePublicKeyPem(): string {
  const fromEnv = process.env.NEXLIFY_LICENSE_PUBLIC_KEY?.trim();
  if (fromEnv) {
    return fromEnv.includes("BEGIN PUBLIC KEY")
      ? fromEnv
      : Buffer.from(fromEnv, "base64").toString("utf8");
  }
  return DEFAULT_LICENSE_PUBLIC_KEY_PEM;
}
`;

fs.writeFileSync(pubOut, ts);
console.log("Wrote public key to", pubOut);
console.log("Private key:", path.join(keysDir, "private.pem"));
console.log("Issue licenses: npm run license:issue -- --email you@co.com --days 365");
