#!/usr/bin/env bash
# Nexlify stream server one-click bootstrap — Ubuntu/Debian
# Sets up: FFmpeg, nginx (no live buffering), HLS dir, optional Redis, Nexlify agent
set -euo pipefail

PANEL_URL="${PANEL_URL:-}"
AGENT_TOKEN="${AGENT_TOKEN:-}"
INSTALL_DIR="${INSTALL_DIR:-/opt/nexlify-agent}"
HLS_DIR="${HLS_DIR:-/var/www/nexlify-hls}"
INSTALL_REDIS="${INSTALL_REDIS:-1}"

echo "[nexlify] Installing stream stack (nginx + FFmpeg + agent)…"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
PACKAGES="curl ca-certificates ffmpeg nginx"
if [ "$INSTALL_REDIS" = "1" ]; then
  PACKAGES="$PACKAGES redis-server"
fi
apt-get install -y -qq $PACKAGES

mkdir -p "$HLS_DIR" "$INSTALL_DIR"
chown -R www-data:www-data "$HLS_DIR" 2>/dev/null || true

# Anti-Freeze nginx: disable live proxy buffering
NGINX_SNIPPET="/etc/nginx/conf.d/nexlify-stream.conf"
cat > "$NGINX_SNIPPET" <<'NGINX'
# Nexlify stream edge — generated by one-click installer
# HLS preferred; live locations must not buffer
location /health {
    return 200 "ok\n";
    add_header Content-Type text/plain;
}
location /hls/ {
    alias /var/www/nexlify-hls/;
    types { application/vnd.apple.mpegurl m3u8; video/mp2t ts; }
    add_header Cache-Control no-cache;
    add_header Access-Control-Allow-Origin *;
}
NGINX

# Ensure default site proxies live without buffering when panel URL is set
if [ -n "$PANEL_URL" ]; then
  PANEL_HOST="$(echo "$PANEL_URL" | sed -E 's#^https?://##' | cut -d/ -f1)"
  cat >> "$NGINX_SNIPPET" <<NGINX2

location ~ ^/live/ {
    proxy_pass ${PANEL_URL};
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_buffering off;
    proxy_request_buffering off;
    proxy_read_timeout 300s;
    add_header Access-Control-Allow-Origin *;
}
NGINX2
fi

nginx -t && systemctl reload nginx || echo "[nexlify] nginx reload skipped — check config manually"

if [ "$INSTALL_REDIS" = "1" ]; then
  systemctl enable redis-server 2>/dev/null || true
  systemctl start redis-server 2>/dev/null || true
  echo "[nexlify] Redis enabled for Fast Zap URL cache (panel should use same Redis host if remote)."
fi

curl -fsSL "${PANEL_URL%/}/scripts/nexlify-stream-agent.sh" -o "$INSTALL_DIR/nexlify-stream-agent.sh" 2>/dev/null || \
  curl -fsSL "https://raw.githubusercontent.com/nexlify/nexlify-panel/main/scripts/nexlify-stream-agent.sh" -o "$INSTALL_DIR/nexlify-stream-agent.sh" || true

chmod +x "$INSTALL_DIR/nexlify-stream-agent.sh" 2>/dev/null || true

cat > /etc/systemd/system/nexlify-agent.service <<EOF
[Unit]
Description=Nexlify Stream Agent
After=network.target nginx.service

[Service]
Type=simple
Environment=PANEL_URL=${PANEL_URL}
Environment=AGENT_TOKEN=${AGENT_TOKEN}
Environment=INSTALL_DIR=${INSTALL_DIR}
ExecStart=${INSTALL_DIR}/nexlify-stream-agent.sh
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable nexlify-agent
systemctl restart nexlify-agent || echo "[nexlify] Start agent after setting PANEL_URL and AGENT_TOKEN"

echo "[nexlify] Done."
echo "[nexlify] HLS directory: $HLS_DIR"
echo "[nexlify] nginx snippet: $NGINX_SNIPPET (proxy_buffering off on /live/)"
echo "[nexlify] Register server in Admin → Servers and paste agent token."
echo "[nexlify] Download full template: Admin → Servers → Recommended nginx config"
