#!/usr/bin/env bash
# Host-agnostic XUI-style split: panel API on :13000, live bytes on a remote edge.
# Media must return 200 + bytes — never 302. See scripts/apply-live-edge-topology.sh
set -euo pipefail

if [ -f /etc/nexlify/server-45-protected ] && [ "${LIVE_ROUTING_FORCE:-}" != "1" ]; then
  echo "Protected host — refusing remote routing rewrite"
  exit 0
fi

REMOTE_EDGE="${NEXLIFY_REMOTE_EDGE:-${REMOTE_EDGE:-}}"
if [ -z "$REMOTE_EDGE" ]; then
  echo "ERROR: set NEXLIFY_REMOTE_EDGE=host:port for remote live-edge mode" >&2
  exit 1
fi
if ! echo "$REMOTE_EDGE" | grep -qE '^[0-9a-zA-Z._-]+:[0-9]+$'; then
  echo "ERROR: NEXLIFY_REMOTE_EDGE must be host:port (got: $REMOTE_EDGE)" >&2
  exit 1
fi

PANEL_LISTEN="${PANEL_LISTEN:-13000}"
if [ -f "${PANEL_DIR:-/opt/nexlify-panel}/.env" ]; then
  # shellcheck disable=SC1091
  . "${PANEL_DIR:-/opt/nexlify-panel}/.env"
  PANEL_LISTEN="${PORT:-${PANEL_PORT:-$PANEL_LISTEN}}"
fi

CONF="/etc/nginx/conf.d/nexlify-live-remote-edge.conf"

# Release :8080 from local Node edge — nginx owns split routing (XUI-style).
pm2 stop nexlify-iptv-edge 2>/dev/null || true
# Do NOT fuser -k :8080 — that kills nginx workers bound on the same port.
sleep 1

cat > "$CONF" <<EOF
# Generated by route-live-to-remote-edge.sh — panel API local, live bytes remote.
upstream nexlify_remote_edge {
    server ${REMOTE_EDGE};
    keepalive 128;
}

upstream nexlify_panel_backend {
    server 127.0.0.1:${PANEL_LISTEN};
    keepalive 256;
}

server {
    listen 8080;
    listen [::]:8080;
    server_name _;

    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_buffering off;
    proxy_request_buffering off;

    location ~ ^/(player_api\.php|get\.php|xmltv\.php|timeshift/|movie/|series/|c/|stalker_portal/|api/) {
        proxy_pass http://nexlify_panel_backend;
        proxy_set_header Host \$host;
        proxy_set_header Authorization \$http_authorization;
        proxy_set_header X-Nexlify-Agent-Server-Id \$http_x_nexlify_agent_server_id;
        proxy_set_header X-Original-Uri \$http_x_original_uri;
        proxy_set_header X-Original-Method \$http_x_original_method;
        proxy_set_header X-Original-Range \$http_x_original_range;
        proxy_set_header X-Real-IP \$remote_addr;
        # Overwrite client-supplied XFF; the remote edge trusts this panel IP.
        proxy_set_header X-Forwarded-For \$remote_addr;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_connect_timeout 10s;
        proxy_read_timeout 300s;
    }

    location ~ ^/(live|timeshift|movie|series)/ {
        proxy_pass http://nexlify_remote_edge;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$remote_addr;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Range \$http_range;
        proxy_set_header User-Agent \$http_user_agent;
        proxy_connect_timeout 10s;
        proxy_send_timeout 3600s;
        proxy_read_timeout 3600s;
        proxy_buffering off;
    }

    location / {
        proxy_pass http://nexlify_panel_backend;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 300s;
    }
}
EOF

rm -f /etc/nginx/conf.d/nexlify-stream-edge.conf /etc/nginx/conf.d/nexlify-stream-extra.conf 2>/dev/null || true

if ! systemctl is-active --quiet nginx 2>/dev/null; then
  systemctl start nginx 2>/dev/null || service nginx start 2>/dev/null || true
fi

nginx -t
if systemctl is-active --quiet nginx 2>/dev/null; then
  systemctl reload nginx 2>/dev/null || nginx -s reload 2>/dev/null || true
else
  systemctl start nginx 2>/dev/null || service nginx start 2>/dev/null || true
fi
echo "remote_routing_ok API→127.0.0.1:${PANEL_LISTEN} live→${REMOTE_EDGE}"
