#!/usr/bin/env bash
# Permanent port fix: sync .env, nginx stream edge, and UFW from current panel config.
# Safe to run after install, deploy, or Admin → Settings → Server & port changes.
#
# Port ownership:
#   nginx     → :80 (and marketing TLS :443 when present)
#   IPTV edge → :8080 / :25461 / optional :443 on IP panels
# These cannot share a TCP port — install-nginx-stream-edge skips edge-owned ports,
# then install-iptv-edge-proxy releases any leftover nginx listens before binding.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# Legacy RTMP was written into conf.d (http{}) and breaks `nginx -t` — always clear it.
rm -f /etc/nginx/conf.d/nexlify-rtmp.conf 2>/dev/null || true

echo "[sync-panel-ports] Ensuring panel .env…"
bash scripts/ensure-panel-env.sh

set -a
# shellcheck disable=SC1091
[ -f .env ] && . ./.env
set +a

BEHIND="${PANEL_BEHIND_NGINX:-1}"
USE_NGINX="${NEXLIFY_USE_NGINX:-1}"
PANEL_LISTEN="${PORT:-${PANEL_PORT:-80}}"

# Keep nginx upstream pointed at the panel listen port (IP installs use :80, domain :13000).
if command -v nginx >/dev/null 2>&1; then
  mkdir -p /etc/nginx/conf.d
  cat > /etc/nginx/conf.d/nexlify-upstream.conf <<UP
# Generated by sync-panel-ports — panel listen port ${PANEL_LISTEN}
upstream nexlify_panel {
    least_conn;
    server 127.0.0.1:${PANEL_LISTEN};
    keepalive 32;
}
UP
fi

if [ "$BEHIND" = "1" ] || [ "$BEHIND" = "true" ] || [ "$USE_NGINX" = "1" ]; then
  if command -v nginx >/dev/null 2>&1; then
    echo "[sync-panel-ports] Installing / refreshing nginx stream edge (skips IPTV-edge ports)…"
    bash scripts/install-nginx-stream-edge.sh
  else
    echo "[sync-panel-ports] WARN: nginx not installed — stream edge vhost skipped"
  fi
else
  echo "[sync-panel-ports] Direct port ${PANEL_LISTEN} mode — panel owns HTTP; nginx only binds extra IPTV ports not owned by edge"
  rm -f /etc/nginx/conf.d/nexlify-stream-edge.conf 2>/dev/null || true
  # Default site listens on :80 and fights the panel on IP installs.
  rm -f /etc/nginx/sites-enabled/default 2>/dev/null || true
  if command -v nginx >/dev/null 2>&1; then
    bash scripts/install-nginx-stream-edge.sh
  fi
fi

echo "[sync-panel-ports] Opening firewall ports…"
bash scripts/nexlify-firewall-ports.sh

if command -v nginx >/dev/null 2>&1; then
  echo "[sync-panel-ports] Refreshing RTMP vhost…"
  bash scripts/install-nginx-rtmp.sh || echo "[sync-panel-ports] WARN: RTMP install skipped"
  echo "[sync-panel-ports] Refreshing extra HTTPS listeners…"
  bash scripts/install-nginx-https-extra-ports.sh || echo "[sync-panel-ports] WARN: extra HTTPS skipped"
  if systemctl is-active --quiet nginx 2>/dev/null; then
    nginx -t && systemctl reload nginx
  else
    nginx -t && systemctl start nginx
  fi
fi

if [ -f scripts/verify-panel-ports.sh ]; then
  bash scripts/verify-panel-ports.sh || echo "[sync-panel-ports] WARN: port verification reported issues (see above)"
fi

LIVE_EDGE_MODE="${NEXLIFY_LIVE_EDGE_MODE:-local}"
LIVE_EDGE_MODE="$(echo "$LIVE_EDGE_MODE" | tr '[:upper:]' '[:lower:]')"
if [ ! -f /etc/nexlify/server-45-protected ] && [ ! -f /etc/nexlify/live-routing.lock ]; then
  if [ -f "$ROOT/scripts/apply-live-edge-topology.sh" ]; then
    echo "[sync-panel-ports] Applying live-edge topology (${LIVE_EDGE_MODE})…"
    PANEL_DIR="$ROOT" bash "$ROOT/scripts/apply-live-edge-topology.sh" || echo "[sync-panel-ports] WARN: topology apply failed"
  fi
fi

echo "[sync-panel-ports] Complete."

# Gzip large Xtream JSON (get_series / get_vod_streams) for XCIPTV
if [[ -f "$ROOT/scripts/enable-nginx-json-gzip.sh" ]]; then
  bash "$ROOT/scripts/enable-nginx-json-gzip.sh" || true
fi

# IPTV edge is installed by deploy / install-iptv-edge-proxy.sh — not on every
# Admin → Servers save (that blocked the panel for minutes while waiting on health).
if [[ "${SYNC_IPTV_EDGE:-0}" == "1" && -f "$ROOT/scripts/install-iptv-edge-proxy.sh" ]]; then
  bash "$ROOT/scripts/install-iptv-edge-proxy.sh" || true
elif [[ "${SYNC_IPTV_EDGE:-0}" == "1" && -f "$ROOT/scripts/fix-panel-https-default.sh" ]]; then
  bash "$ROOT/scripts/fix-panel-https-default.sh" || true
fi
