import type { AvatarConfig } from "@/lib/avatar-config";
import { DEFAULT_AVATAR_CONFIG } from "@/lib/avatar-config";

export const SKIN_TONES = [
  "#f5c6a5",
  "#e8b796",
  "#d4a574",
  "#c68642",
  "#8d5524",
  "#5c3d2e",
  "#ffdbac",
  "#f1c27d",
];

export const HAIR_COLORS = [
  "#1a1a1a",
  "#3d2314",
  "#6b4423",
  "#b8860b",
  "#d4a574",
  "#c0c0c0",
  "#e8b796",
  "#8b0000",
];

export const CLOTHING_COLORS = [
  "#2563eb",
  "#dc2626",
  "#16a34a",
  "#7c3aed",
  "#ea580c",
  "#0d9488",
  "#1f2937",
  "#f8fafc",
  "#fbbf24",
  "#ec4899",
  "#64748b",
  "#78350f",
];

export const BACKGROUND_COLORS = [
  "#e8f4fc",
  "#fef3c7",
  "#fce7f3",
  "#d1fae5",
  "#e0e7ff",
  "#fed7aa",
  "#f3f4f6",
  "#1e293b",
  "#0f766e",
  "#7c2d12",
  "#4c1d95",
  "#ff4500",
];

export const SKIN_STYLES = ["round", "oval", "square"] as const;
export const HAIR_STYLES = ["none", "short", "spiky", "long", "buzz", "curly", "ponytail", "bald"] as const;
export const SHIRT_STYLES = [
  "tee",
  "polo",
  "hoodie",
  "jacket",
  "vest",
  "tank",
  "dress-shirt",
  "sweater",
  "blazer",
  "cardigan",
  "bomber",
  "turtleneck",
  "crop-top",
  "overalls",
  "apron",
] as const;
export const PANTS_STYLES = ["jeans", "shorts", "cargo", "slacks", "skirt", "sweatpants"] as const;
export const SHOE_STYLES = ["none", "sneakers", "loafers", "heels", "sandals", "flip-flops"] as const;
export const BOOT_STYLES = ["none", "ankle", "combat", "cowboy", "rain", "hiking", "work"] as const;
export const HAT_STYLES = ["none", "cap", "beanie", "fedora", "cowboy", "top", "beret", "headphones"] as const;
export const EYE_STYLES = ["round", "happy", "wide", "sleepy", "dots"] as const;
export const MOUTH_STYLES = ["smile", "neutral", "open", "smirk", "laugh"] as const;
export const ACCESSORY_STYLES = [
  "none",
  "glasses",
  "round-glasses",
  "thick-glasses",
  "sunglasses",
  "aviators",
  "necklace",
  "tie",
  "scarf",
  "badge",
] as const;

export type AvatarPreset = {
  id: string;
  label: string;
  config: AvatarConfig;
};

function preset(label: string, patch: Partial<AvatarConfig>): AvatarPreset {
  const id = label.toLowerCase().replace(/\s+/g, "-");
  return {
    id,
    label,
    config: { ...DEFAULT_AVATAR_CONFIG, ...patch },
  };
}

export const AVATAR_PRESETS: AvatarPreset[] = [
  preset("Classic", {}),
  preset("Night owl", {
    backgroundColor: "#1e293b",
    hat: "headphones",
    hatColor: "#374151",
    shirt: "hoodie",
    shirtColor: "#4c1d95",
    pantsColor: "#1f2937",
    hair: "short",
    hairColor: "#1a1a1a",
  }),
  preset("Sunset", {
    backgroundColor: "#fed7aa",
    shirt: "tee",
    shirtColor: "#ff4500",
    pants: "shorts",
    pantsColor: "#78350f",
    hat: "cap",
    hatColor: "#dc2626",
  }),
  preset("Forest", {
    backgroundColor: "#d1fae5",
    shirt: "jacket",
    shirtColor: "#16a34a",
    pants: "cargo",
    pantsColor: "#365314",
    boots: "hiking",
    bootsColor: "#4a3728",
  }),
  preset("Ocean", {
    backgroundColor: "#e8f4fc",
    shirt: "polo",
    shirtColor: "#0d9488",
    pants: "jeans",
    pantsColor: "#1e3a5f",
    accessory: "sunglasses",
  }),
  preset("Formal", {
    backgroundColor: "#f3f4f6",
    shirt: "dress-shirt",
    shirtColor: "#f8fafc",
    pants: "slacks",
    pantsColor: "#1f2937",
    accessory: "tie",
    shoes: "loafers",
    shoesColor: "#1a1a1a",
  }),
  preset("Retro", {
    backgroundColor: "#fce7f3",
    hair: "ponytail",
    hairColor: "#ec4899",
    shirt: "sweater",
    shirtColor: "#7c3aed",
    pants: "skirt",
    pantsColor: "#c33764",
  }),
  preset("Street", {
    backgroundColor: "#fef3c7",
    hat: "beanie",
    hatColor: "#fbbf24",
    shirt: "hoodie",
    shirtColor: "#1f2937",
    pants: "sweatpants",
    pantsColor: "#64748b",
    boots: "combat",
    bootsColor: "#1a1a1a",
  }),
  preset("Lime pop", {
    backgroundColor: "#84cc16",
    skinTone: "#f5c6a5",
    hair: "spiky",
    hairColor: "#1a1a1a",
    eyes: "happy",
    mouth: "laugh",
    accessory: "round-glasses",
    shirt: "tee",
    shirtColor: "#f8fafc",
    pants: "jeans",
    pantsColor: "#1e3a5f",
  }),
  preset("Violet", {
    backgroundColor: "#a855f7",
    hair: "curly",
    hairColor: "#4c1d95",
    eyes: "wide",
    mouth: "smile",
    shirt: "hoodie",
    shirtColor: "#7c3aed",
    pants: "cargo",
    pantsColor: "#312e81",
  }),
  preset("Coral", {
    backgroundColor: "#fb7185",
    hair: "buzz",
    hairColor: "#1a1a1a",
    accessory: "aviators",
    shirt: "polo",
    shirtColor: "#fff7ed",
    pants: "shorts",
    pantsColor: "#9a3412",
  }),
  preset("Sky", {
    backgroundColor: "#38bdf8",
    hair: "long",
    hairColor: "#0ea5e9",
    eyes: "dots",
    mouth: "neutral",
    hat: "cap",
    hatColor: "#f8fafc",
    shirt: "tank",
    shirtColor: "#0f766e",
    pants: "shorts",
    pantsColor: "#134e4a",
  }),
  preset("Gold", {
    backgroundColor: "#fbbf24",
    hair: "ponytail",
    hairColor: "#78350f",
    eyes: "round",
    mouth: "smirk",
    accessory: "thick-glasses",
    shirt: "sweater",
    shirtColor: "#dc2626",
    pants: "skirt",
    pantsColor: "#7c2d12",
  }),
  preset("Mint", {
    backgroundColor: "#34d399",
    hair: "none",
    skinTone: "#8d5524",
    eyes: "sleepy",
    mouth: "open",
    shirt: "vest",
    shirtColor: "#064e3b",
    pants: "slacks",
    pantsColor: "#14532d",
  }),
  preset("Cherry", {
    backgroundColor: "#be123c",
    hair: "long",
    hairColor: "#881337",
    eyes: "wide",
    mouth: "smile",
    accessory: "aviators",
    shirt: "hoodie",
    shirtColor: "#1f2937",
    pants: "jeans",
    pantsColor: "#0f172a",
  }),
  preset("Indigo", {
    backgroundColor: "#6366f1",
    hair: "buzz",
    hairColor: "#312e81",
    eyes: "dots",
    mouth: "neutral",
    shirt: "polo",
    shirtColor: "#e0e7ff",
    pants: "cargo",
    pantsColor: "#1e1b4b",
  }),
  preset("Peach", {
    backgroundColor: "#fdba74",
    hair: "curly",
    hairColor: "#c2410c",
    eyes: "happy",
    mouth: "laugh",
    blush: true,
    shirt: "tee",
    shirtColor: "#fff7ed",
    pants: "shorts",
    pantsColor: "#9a3412",
  }),
  preset("Slate pro", {
    backgroundColor: "#475569",
    hair: "short",
    hairColor: "#94a3b8",
    accessory: "thick-glasses",
    shirt: "dress-shirt",
    shirtColor: "#f8fafc",
    pants: "slacks",
    pantsColor: "#1e293b",
    shoes: "loafers",
    shoesColor: "#1a1a1a",
  }),
  preset("Aqua", {
    backgroundColor: "#06b6d4",
    hair: "ponytail",
    hairColor: "#0891b2",
    eyes: "round",
    mouth: "smirk",
    hat: "cap",
    hatColor: "#f0fdfa",
    shirt: "tank",
    shirtColor: "#134e4a",
    pants: "shorts",
    pantsColor: "#164e63",
  }),
  preset("Plum", {
    backgroundColor: "#9333ea",
    hair: "spiky",
    hairColor: "#581c87",
    eyes: "sleepy",
    mouth: "open",
    shirt: "sweater",
    shirtColor: "#fae8ff",
    pants: "sweatpants",
    pantsColor: "#3b0764",
    boots: "combat",
    bootsColor: "#1a1a1a",
  }),
  preset("Sand", {
    backgroundColor: "#d6d3d1",
    hair: "bald",
    skinTone: "#d4a574",
    eyes: "wide",
    mouth: "neutral",
    accessory: "round-glasses",
    shirt: "vest",
    shirtColor: "#78716c",
    pants: "jeans",
    pantsColor: "#44403c",
  }),
  preset("Neon", {
    backgroundColor: "#0f172a",
    hair: "spiky",
    hairColor: "#22d3ee",
    eyes: "wide",
    mouth: "laugh",
    accessory: "sunglasses",
    shirt: "hoodie",
    shirtColor: "#ec4899",
    pants: "cargo",
    pantsColor: "#581c87",
  }),
  preset("Copper", {
    backgroundColor: "#ea580c",
    hair: "curly",
    hairColor: "#451a03",
    eyes: "happy",
    mouth: "smile",
    shirt: "jacket",
    shirtColor: "#1c1917",
    pants: "jeans",
    pantsColor: "#292524",
  }),
  preset("Frost", {
    backgroundColor: "#e0f2fe",
    hair: "long",
    hairColor: "#e2e8f0",
    eyes: "sleepy",
    mouth: "neutral",
    hat: "beanie",
    hatColor: "#38bdf8",
    shirt: "sweater",
    shirtColor: "#0c4a6e",
    pants: "slacks",
    pantsColor: "#334155",
  }),
  preset("Berry", {
    backgroundColor: "#86198f",
    hair: "ponytail",
    hairColor: "#f0abfc",
    eyes: "dots",
    mouth: "smirk",
    shirt: "dress-shirt",
    shirtColor: "#faf5ff",
    pants: "skirt",
    pantsColor: "#4a044e",
  }),
  preset("Olive", {
    backgroundColor: "#65a30d",
    hair: "short",
    hairColor: "#1a2e05",
    eyes: "round",
    mouth: "open",
    accessory: "glasses",
    shirt: "polo",
    shirtColor: "#fefce8",
    pants: "shorts",
    pantsColor: "#365314",
  }),
  preset("Studio", {
    backgroundColor: "#18181b",
    hair: "buzz",
    hairColor: "#fafafa",
    eyes: "round",
    mouth: "neutral",
    accessory: "thick-glasses",
    hat: "headphones",
    shirt: "hoodie",
    shirtColor: "#27272a",
    pants: "sweatpants",
    pantsColor: "#09090b",
  }),
  preset("Candy", {
    backgroundColor: "#f472b6",
    hair: "spiky",
    hairColor: "#fbbf24",
    eyes: "happy",
    mouth: "laugh",
    blush: true,
    shirt: "tee",
    shirtColor: "#fff",
    pants: "shorts",
    pantsColor: "#db2777",
  }),
  preset("Denim", {
    backgroundColor: "#3b82f6",
    hat: "cap",
    hatColor: "#1e3a8a",
    hair: "short",
    hairColor: "#1e3a8a",
    eyes: "wide",
    mouth: "smile",
    shirt: "vest",
    shirtColor: "#dbeafe",
    pants: "jeans",
    pantsColor: "#1e40af",
  }),
  preset("Blazer", {
    backgroundColor: "#e0e7ff",
    shirt: "blazer",
    shirtColor: "#1e3a8a",
    pants: "slacks",
    pantsColor: "#0f172a",
    shoes: "loafers",
    accessory: "tie",
  }),
  preset("Cardigan", {
    backgroundColor: "#fef3c7",
    hair: "long",
    hairColor: "#6b4423",
    shirt: "cardigan",
    shirtColor: "#92400e",
    pants: "jeans",
    pantsColor: "#1e3a5f",
    boots: "ankle",
  }),
  preset("Bomber", {
    backgroundColor: "#1e293b",
    shirt: "bomber",
    shirtColor: "#334155",
    pants: "cargo",
    pantsColor: "#0f172a",
    hat: "cap",
    hatColor: "#dc2626",
  }),
  preset("Chef", {
    backgroundColor: "#fff7ed",
    shirt: "apron",
    shirtColor: "#f8fafc",
    pants: "slacks",
    pantsColor: "#1f2937",
    hat: "none",
    accessory: "none",
  }),
  preset("Tech lead", {
    backgroundColor: "#0f766e",
    shirt: "turtleneck",
    shirtColor: "#134e4a",
    pants: "slacks",
    pantsColor: "#042f2e",
    accessory: "round-glasses",
    hat: "none",
  }),
  preset("Streamer", {
    backgroundColor: "#4c1d95",
    hat: "headphones",
    shirt: "hoodie",
    shirtColor: "#7c3aed",
    pants: "sweatpants",
    pantsColor: "#312e81",
    accessory: "aviators",
  }),
];

function hashPick<T>(seed: string, arr: readonly T[]): T {
  let h = 0;
  for (let i = 0; i < seed.length; i++) h = (h * 31 + seed.charCodeAt(i)) | 0;
  return arr[Math.abs(h) % arr.length];
}

/** Deterministic Reddit-style character from username when user has no saved avatar. */
export function avatarConfigFromUsername(username: string): AvatarConfig {
  const seed = username.trim().toLowerCase() || "user";
  return {
    ...DEFAULT_AVATAR_CONFIG,
    backgroundColor: hashPick(seed, BACKGROUND_COLORS),
    skinTone: hashPick(seed + "s", SKIN_TONES),
    hair: hashPick(seed + "h", HAIR_STYLES),
    hairColor: hashPick(seed + "hc", HAIR_COLORS),
    shirt: hashPick(seed + "sh", SHIRT_STYLES),
    shirtColor: hashPick(seed + "sc", CLOTHING_COLORS),
    pants: hashPick(seed + "p", PANTS_STYLES),
    pantsColor: hashPick(seed + "pc", CLOTHING_COLORS),
    hat: hashPick(seed + "hat", HAT_STYLES),
    hatColor: hashPick(seed + "hatc", CLOTHING_COLORS),
    eyes: hashPick(seed + "e", EYE_STYLES),
    mouth: hashPick(seed + "m", MOUTH_STYLES),
    blush: true,
  };
}

export function randomAvatarConfig(): AvatarConfig {
  const preset = AVATAR_PRESETS[Math.floor(Math.random() * AVATAR_PRESETS.length)];
  return { ...preset.config };
}

export const CUSTOMIZER_TABS = [
  { id: "outfits", label: "Outfits" },
  { id: "face", label: "Face" },
  { id: "eyes", label: "Eyes" },
  { id: "mouth", label: "Mouth" },
  { id: "hair", label: "Hair" },
  { id: "tops", label: "Tops" },
  { id: "bottoms", label: "Bottoms" },
  { id: "hats", label: "Hats" },
  { id: "extras", label: "Extras" },
  { id: "background", label: "Background" },
] as const;
