/** Common TMDB API language/locale codes (ISO 639-1 + region). */
export const TMDB_LANGUAGE_OPTIONS = [
  { value: "en-US", label: "English (US)" },
  { value: "en-GB", label: "English (UK)" },
  { value: "es-ES", label: "Spanish (Spain)" },
  { value: "es-MX", label: "Spanish (Mexico)" },
  { value: "fr-FR", label: "French" },
  { value: "de-DE", label: "German" },
  { value: "it-IT", label: "Italian" },
  { value: "pt-BR", label: "Portuguese (Brazil)" },
  { value: "pt-PT", label: "Portuguese (Portugal)" },
  { value: "nl-NL", label: "Dutch" },
  { value: "pl-PL", label: "Polish" },
  { value: "ru-RU", label: "Russian" },
  { value: "uk-UA", label: "Ukrainian" },
  { value: "tr-TR", label: "Turkish" },
  { value: "ar-SA", label: "Arabic" },
  { value: "he-IL", label: "Hebrew" },
  { value: "hi-IN", label: "Hindi" },
  { value: "ja-JP", label: "Japanese" },
  { value: "ko-KR", label: "Korean" },
  { value: "zh-CN", label: "Chinese (Simplified)" },
  { value: "zh-TW", label: "Chinese (Traditional)" },
  { value: "th-TH", label: "Thai" },
  { value: "vi-VN", label: "Vietnamese" },
  { value: "id-ID", label: "Indonesian" },
  { value: "ms-MY", label: "Malay" },
  { value: "sv-SE", label: "Swedish" },
  { value: "no-NO", label: "Norwegian" },
  { value: "da-DK", label: "Danish" },
  { value: "fi-FI", label: "Finnish" },
  { value: "cs-CZ", label: "Czech" },
  { value: "ro-RO", label: "Romanian" },
  { value: "hu-HU", label: "Hungarian" },
  { value: "bg-BG", label: "Bulgarian" },
  { value: "hr-HR", label: "Croatian" },
  { value: "sk-SK", label: "Slovak" },
  { value: "el-GR", label: "Greek" },
  { value: "ca-ES", label: "Catalan" },
  { value: "sr-RS", label: "Serbian" },
  { value: "sl-SI", label: "Slovenian" },
  { value: "lt-LT", label: "Lithuanian" },
  { value: "lv-LV", label: "Latvian" },
  { value: "et-EE", label: "Estonian" },
] as const;
