-- M3U auto-sync + watch-folder import scope (idempotent)
ALTER TABLE "M3uSyncJob" ADD COLUMN IF NOT EXISTS "updateNames" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "M3uSyncJob" ADD COLUMN IF NOT EXISTS "overwriteCategories" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "M3uSyncJob" ADD COLUMN IF NOT EXISTS "autoBouquet" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "M3uSyncJob" ADD COLUMN IF NOT EXISTS "bouquetIds" TEXT NOT NULL DEFAULT '';
ALTER TABLE "M3uSyncJob" ADD COLUMN IF NOT EXISTS "onDemand" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "M3uSyncJob" ADD COLUMN IF NOT EXISTS "removeDuplicates" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "M3uSyncJob" ADD COLUMN IF NOT EXISTS "isAdult" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "M3uSyncJob" ADD COLUMN IF NOT EXISTS "groupFilter" TEXT NOT NULL DEFAULT '';
ALTER TABLE "M3uSyncJob" ADD COLUMN IF NOT EXISTS "createMissing" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "WatchFolder" ADD COLUMN IF NOT EXISTS "groupFilter" TEXT NOT NULL DEFAULT '';
ALTER TABLE "WatchFolder" ADD COLUMN IF NOT EXISTS "createMissing" BOOLEAN NOT NULL DEFAULT true;
